import type { ProjectConfig } from "@/types";

export const PROJECT_CONFIGS: ProjectConfig[] = [
  {
    key: "archeon",
    slug: "archeon-ai-second-brain",
    liveDemo: true,
    images: true,
    technologies: [
      "Graph RAG",
      "Neo4j",
      "Graphiti",
      "FastAPI",
      "NestJS",
      "pgvector",
      "LLaMA 3.1",
      "Celery",
      "React Native",
      "Next.js",
      "TypeScript",
      "Python",
      "Docker",
      "Prometheus",
      "Grafana",
    ],
  },
  {
    key: "chat",
    slug: "real-time-chat-application",
    liveDemo: true,
    technologies: [
      "Next.js 15",
      "NestJS",
      "Socket.IO",
      "PostgreSQL",
      "Prisma",
      "TypeScript",
      "Tailwind CSS",
      "Cloudflare R2",
      "Docker",
      "Ansible",
    ],
  },
  {
    key: "syntrix",
    slug: "syntrix-legal-services-platform",
    liveDemo: true,
    images: true,
    technologies: [
      "Next.js 15",
      "React 19",
      "NestJS 11",
      "TypeScript 5",
      "Tailwind CSS 4",
      "Docker Compose",
      "Yarn Workspaces",
      "ESLint",
      "Prettier",
      "Jest",
    ],
  },
  {
    key: "coverLetter",
    slug: "ai-powered-cover-letter-generator",
    images: true,
    technologies: [
      "React 18",
      "TypeScript",
      "Plasmo",
      "NestJS 11",
      "Prisma",
      "OpenAI (DeepSeek)",
      "Google OAuth",
      "Passport.js",
      "JWT",
      "PDF-Lib",
      "Tesseract.js",
      "jsPDF",
      "Docker",
      "PostgreSQL",
    ],
  },
  {
    key: "voiceTrain",
    slug: "voice-controlled-train-route-finder",
    technologies: [
      "Python 3.x",
      "BERT (Transformers)",
      "spaCy 3.7",
      "Neo4j 5.25",
      "TensorFlow/Keras",
      "Speech Recognition",
      "PyAudio",
      "Vosk (Offline STT)",
      "Pandas",
      "Jupyter Notebook",
      "Docker",
      "Graph Algorithms (Dijkstra)",
    ],
  },
  {
    key: "rlSuite",
    slug: "reinforcement-learning-suite",
    technologies: [
      "Python 3.x",
      "Gymnasium",
      "PyTorch",
      "NumPy",
      "TensorBoard",
      "OpenCV",
      "ALE",
      "Pygame",
      "Matplotlib",
      "CUDA",
    ],
  },
  {
    key: "jumbot",
    slug: "jumbot-automated-deployment-bot",
    images: true,
    technologies: [
      "BoltJS",
      "NestJS",
      "RabbitMQ",
      "MongoDB",
      "TypeORM",
      "Docker",
      "Kubernetes",
      "GitLab CI/CD",
      "Slack API",
      "Node.js",
      "TypeScript",
      "Bash Scripting",
      "PostgreSQL",
    ],
  },
] as const;

export const MAX_VISIBLE_TECHNOLOGIES = 8;
