export const messagesEn = {
  // General
  "common.scroll": "Scroll",
  "common.available": "Available for new projects",
  "common.contactMe": "Contact me",
  "common.viewProjects": "View my projects",
  "common.discover": "Discover →",
  "common.sendMessage": "Send message",
  "common.name": "Name",
  "common.email": "Email",
  "common.message": "Message",
  "common.sending": "Sending...",
  "common.contactInfo": "Contact Information",
  "common.professionalLinks": "Professional Links",
  "common.downloadCv": "Download my resume",
  "common.githubProfile": "GitHub Profile",
  "common.linkedinProfile": "LinkedIn Profile",
  "common.location": "Location",
  "common.languages": "Languages",

  // Hero
  "hero.title": "Mustapha",
  "hero.subtitle": "Software Architect",
  "hero.description.part1": "Passionate about full-stack development and artificial intelligence.",
  "hero.description.part2": "I turn complex ideas into ",
  "hero.description.highlight": "innovative products",

  // Resume header
  "resume.title": "Software Architect",
  "resume.location": "Toulouse, Occitanie, France",

  // About
  "about.title": "About me",
  "about.presentation": "Presentation",
  "about.presentation.p1": "Software engineer passionate about full-stack development and AI. I combine technical expertise and product vision to build impactful, innovative solutions.",
  "about.presentation.p2": "I constantly experiment with emerging technologies (RAG, blockchain, NLP) and transform complex ideas into real products, from design to large-scale deployment.",
  "about.location": "Location",
  "about.location.value": "Toulouse, Occitanie, France",
  "about.languages": "Languages",
  "about.languages.items": "🇫🇷 French (Native);🇦🇪 Arabic (Native);🇪🇸 Spanish (Native);🇪🇸 Catalan (Native);🇬🇧 English (Fluent);🇮🇹 Italian (Conv.)",
  "about.education": "Education",
  "about.education.items": "• Master Software Architect - EPITECH;• Bachelor DevOps - EPSI (Honors);• Web Developer - SIMPLON",

  // Contact
  "contact.title": "Contact Me",
  "contact.alert": "Message sent! (Feature to implement)",
  "contact.success": "Message sent successfully! I'll get back to you soon.",
  "contact.error": "Failed to send message. Please try again or contact me directly.",
  "contact.footer": "© 2025 Mustapha El Hachmi Mahti. All rights reserved.",

  // Sections
  "sections.experiences": "Professional Experience",
  "sections.projects": "Projects",
  "sections.skills": "Skills",

  // Labels
  "labels.stack": "Stack",

  // Experiences (EN)
  "exp.actual.title": "Full Stack Developer",
  "exp.actual.company": "Groupe Actual",
  "exp.actual.location": "Toulouse",
  "exp.actual.period": "September 2022 — September 2025",
  "exp.actual.points": "Web Development: Designed and built complex React/TypeScript apps (50,000+ users) with advanced UIs and optimized state management;Mobile Applications: Cross-platform iOS/Android with React Native/Expo (250,000+ downloads);Backend Architecture: Designed NestJS microservices with RESTful APIs, PostgreSQL/Redis data layers;Performance & Scalability: +30% performance gains, caching and real-time monitoring;Data Engineering: BigQuery integration for business analytics and highly available data pipelines",
  "exp.actual.stack": "React, TypeScript, React Native, NestJS (NodeJS), MySQL, Redis, GCP",

  "exp.bizness.title": "Full Stack Developer",
  "exp.bizness.company": "Groupe Bizness",
  "exp.bizness.location": "Toulouse",
  "exp.bizness.period": "January 2022 — August 2022",
  "exp.bizness.points": "Microservices Architecture: Event-driven design with multi-source aggregation APIs;Real-time Apps: WebSockets and Server-Sent Events for collaborative interfaces;Database & APIs: APIs built with SAP HANA backend",
  "exp.bizness.stack": "Node.js, WebSockets, SAP HANA",

  "exp.jump.title": "Full Stack Developer",
  "exp.jump.company": "Société JUMP",
  "exp.jump.location": "Toulouse",
  "exp.jump.period": "May 2021 — July 2021",
  "exp.jump.points": "E2E test automation with Selenium WebDriver, Cucumber JS and Gherkin;Custom Slack commands with Bolt JS and NestJS;Automated workflows to boost team productivity",
  "exp.jump.stack": "Selenium, Cucumber JS, Bolt JS, NestJS",

  "exp.syntrix.title": "Co-founder & CTO",
  "exp.syntrix.company": "Syntrix - Compliance & Anti-Fraud Platform",
  "exp.syntrix.location": "Remote",
  "exp.syntrix.period": "July 2023",
  "exp.syntrix.points": "SaaS compliance platform (3 enterprise clients). Clients: Al Fardan Exchange and law firms.;Backend Microservices: NestJS modules (FATCA/CRS) and CoreBanking integration;Web Apps: NextJS (React) interface for automated KYC portal and compliance tools;Real-time Systems: Anti-fraud module with incident detection and automated alerting",
  "exp.syntrix.stack": "React (NextJS), NestJS (NodeJS), PostgreSQL, Redis, Kubernetes, Rabbitmq",

  // Projects
  "project.chat.title": "Real-Time Chat Application",
  "project.chat.description": "Production-ready full-stack chat platform with Google OAuth, direct messaging, group chats, and real-time media sharing.",
  "project.chat.category": "Full-Stack / Real-Time",
  "project.chat.impact": "Monorepo with 100+ files, 95% TypeScript",
  "project.chat.fullDescription": "A sophisticated enterprise-grade messaging platform built with modern technologies, featuring Google OAuth authentication, direct messaging, group chats with up to 50 members, and real-time media sharing capabilities. The application employs a monorepo architecture with TypeScript throughout (95% of codebase), ensuring complete type safety across the entire stack. Deployed with Docker containerization and Ansible automation for production-ready infrastructure.",
  "project.chat.features": "Google OAuth 2.0 authentication with secure JWT token management and refresh tokens;Real-time bidirectional messaging via WebSockets with Socket.IO and automatic reconnection;Group chats supporting up to 50 concurrent members with role-based permissions;Media sharing with drag-and-drop support (images, GIFs) and presigned URL generation;Typing indicators showing active typists in real-time with debouncing;Message read receipts and delivery status tracking across multiple users;Online/offline status tracking with presence system and last seen timestamps;Infinite scroll for message history with cursor-based pagination;Optimistic UI updates for instant feedback and responsive user experience;Full-screen media viewer with keyboard navigation and touch gestures;Mobile-first responsive design with Tailwind CSS and shadcn/ui components;User search and discovery with real-time filtering;Profile management (bio, website, avatar) with image optimization;Message pagination for performance optimization on large conversations;Real-time notifications for new messages and mentions",
  "project.chat.challenges": "Custom WebSocket JWT authentication adapter - Built secure middleware for verifying JWT tokens on WebSocket handshake, enabling authentication for real-time connections;Cursor-based pagination strategy - Implemented efficient message history loading using database cursors instead of offset pagination, improving performance by 70% on large datasets;Scalable media storage architecture - Designed and integrated Cloudflare R2 (S3-compatible) with presigned URLs for secure, scalable media delivery without server bottleneck;Real-time state synchronization - Solved complex problem of keeping message state consistent across multiple connected clients using Socket.IO rooms and event broadcasting;Room-based message routing - Developed automatic user subscription system to personal and group rooms on connection for targeted message delivery without overhead;Multi-user read receipt tracking - Implemented efficient read receipt system tracking individual read status for each user in group chats without N+1 query problems;WebSocket connection management - Built robust reconnection logic with exponential backoff and state recovery after network interruptions;Database schema optimization - Designed Prisma models with strategic indexing on frequently queried fields (email, username, roomId, createdAt) for sub-50ms query times",

  "project.syntrix.title": "Syntrix - Legal Services Platform",
  "project.syntrix.description": "Modern full-stack platform for law firms featuring client management, secure document handling, and planned KYC verification system for regulatory compliance.",
  "project.syntrix.category": "Full-Stack / Legal Tech",
  "project.syntrix.impact": "Monorepo architecture with 72.8% TypeScript coverage",
  "project.syntrix.fullDescription": "An enterprise-grade legal services platform designed for law firms and independent attorneys to digitalize their practice. Built with a modern monorepo architecture using Yarn Workspaces, the platform features a NestJS backend API and Next.js frontend with React 19. The application is containerized with Docker and includes comprehensive testing, code quality tools, and follows industry best practices. Designed with security and compliance in mind, with planned KYC/AML verification capabilities to meet legal industry regulatory requirements.",
  "project.syntrix.features": "Modern monorepo architecture with Yarn Workspaces for efficient code sharing and dependency management;Next.js 15 frontend with App Router, Server Components, and React 19 for optimal performance;NestJS 11 backend with modular architecture, dependency injection, and TypeScript type safety;Responsive mobile-first design with Tailwind CSS 4 for seamless experience across all devices;Docker Compose configuration for consistent development and production environments;Interactive CLI menu for easy project startup and environment selection;Automated code formatting with Prettier across the entire codebase;Comprehensive ESLint configuration with TypeScript-specific rules and recommended practices;Jest testing infrastructure for unit tests, E2E tests, and code coverage reporting;Hot reload and fast refresh for instant feedback during development;Next.js Image optimization with automatic lazy loading and responsive images;Environment variable management with validation and type safety;Production-ready deployment configuration for Vercel and AWS;Geist font family integration for modern, professional typography;Code splitting and tree shaking for optimal bundle sizes",
  "project.syntrix.challenges": "Monorepo configuration - Architected scalable Yarn Workspaces setup managing multiple applications (front/back) with shared dependencies, reducing bundle size by 40% through package deduplication;TypeScript strict mode across stack - Enforced strict type checking throughout 72.8% TypeScript codebase, eliminating runtime type errors and improving IDE intellisense;Docker multi-service orchestration - Designed Docker Compose configuration managing frontend, backend, and database services with proper networking, volume persistence, and health checks;Development workflow optimization - Built custom interactive CLI tool with Inquirer for streamlined project startup, reducing context switching and improving developer experience;Next.js 15 App Router migration - Successfully implemented new App Router architecture with server and client components, optimizing initial page load by 50%;Code quality automation - Integrated ESLint with TypeScript parser and Prettier for automated formatting, enforcing consistent code style across team contributions;Testing strategy implementation - Established comprehensive testing infrastructure with Jest supporting unit tests, integration tests, and E2E testing with coverage reporting;Build optimization - Configured SWC compiler for faster builds (20x faster than Babel) and optimized production bundles with tree shaking",
  "project.syntrix.plannedFeatures": "KYC/AML Module - Complete Know Your Customer verification system with document upload, OCR verification, identity validation, and compliance screening for regulatory requirements;Client Portal - Secure dashboard for clients to view case status, upload documents, and communicate with attorneys;Document Management System - Centralized secure storage with version control, access permissions, and audit trail for legal documents;Appointment Scheduling - Calendar integration with automated reminders and conflict detection for client meetings;Billing & Invoicing - Time tracking, expense management, and automated invoice generation with payment processing;Case Management - Comprehensive system for tracking cases, deadlines, hearings, and associated documents with workflow automation;Secure Messaging - End-to-end encrypted communication between attorneys and clients with read receipts and file sharing;Role-Based Access Control - Granular permission system for partners, associates, paralegals, and clients;AML Screening Integration - Automated screening against international sanctions lists and PEP databases;GDPR/Privacy Compliance - Data protection features including data export, deletion, consent management, and audit logs;Multi-language Support - Internationalization for serving clients in multiple jurisdictions;Analytics Dashboard - Business intelligence with case statistics, revenue tracking, and performance metrics",

  "project.coverLetter.title": "AI-Powered Cover Letter Generator - Chrome Extension",
  "project.coverLetter.description": "Intelligent Chrome extension that automatically generates personalized cover letters by analyzing job postings in real-time and matching them with user resumes using advanced AI technology.",
  "project.coverLetter.category": "Full-Stack / Browser Extension / AI",
  "project.coverLetter.impact": "Monorepo with 92.8% TypeScript - Production browser extension",
  "project.coverLetter.fullDescription": "A sophisticated AI-powered Chrome extension that revolutionizes the job application process by automatically generating tailored cover letters. The extension intelligently scrapes job posting content from any careers page, analyzes the requirements using AI, and creates personalized cover letters that align perfectly with the candidate's resume. Built with a monorepo architecture featuring a React-based Chrome extension frontend and a robust NestJS backend API, the application leverages DeepSeek AI for natural language processing and supports multi-language generation, matching the job posting's language automatically.",
  "project.coverLetter.features": "Real-time job posting extraction from any career website using content scripts and DOM manipulation;Intelligent HTML parsing to extract job title, company, description, requirements, and qualifications;AI-powered cover letter generation using DeepSeek LLM with customizable prompts and instructions;Automatic language detection and matching - generates cover letters in the same language as job posting;Google OAuth 2.0 authentication with secure JWT token management and refresh token rotation;Resume upload and OCR processing with Tesseract.js for extracting text from PDF documents;PDF parsing capabilities to read existing resume documents and extract structured content;Custom instruction system allowing users to emphasize specific skills or adjust tone/length;One-click copy to clipboard functionality for instant application submission;PDF export feature to download generated cover letters in professional format;Chrome extension popup interface with modern glassmorphic design and gradient backgrounds;Local storage caching for last generated letter to prevent unnecessary API calls;Tab-based navigation (Generate, Profile, Settings) with smooth transitions;Status messages and loading states with real-time progress indicators;Resume content storage and management in PostgreSQL database with Prisma;RESTful API backend with proper validation using class-validator and class-transformer;Docker containerization for consistent development and production environments;Axios interceptors for automatic authentication token injection and error handling;Chrome extension permissions for tabs, storage, scripting, and active tab access;Background script for persistent job details extraction across tabs",
  "project.coverLetter.challenges": "Cross-origin content scraping - Implemented Chrome extension content scripts with proper permissions (host_permissions for https://*/*) to inject scripts into job posting pages and extract structured data from diverse HTML layouts across different career platforms;Dynamic website parsing - Built robust DOM traversal algorithms to handle varying HTML structures from different companies (LinkedIn, Indeed, Greenhouse, Lever, etc.), using multiple fallback selectors to ensure reliable job details extraction;AI prompt engineering - Crafted sophisticated multi-part prompts that analyze both raw HTML and extracted text content (up to 120K characters), instructing DeepSeek AI to generate authentic cover letters without inventing experience, maintaining 250-350 word length constraints;Resume OCR accuracy - Integrated Tesseract.js for optical character recognition on scanned PDF resumes, implementing preprocessing techniques to improve text extraction accuracy from various document formats and layouts;Chrome extension authentication flow - Solved complex authentication challenge by implementing secure JWT token storage in chrome.storage.local, with automatic token refresh before API calls and seamless Google OAuth redirect handling;PDF generation in browser - Implemented client-side PDF creation using jsPDF library, formatting cover letter content with proper margins, fonts, and professional styling without backend dependency;Extension state management - Designed React hooks pattern (useCoverLetterGenerator, useAuth, useApi) for managing complex asynchronous workflows including tab querying, message passing, and API calls within Chrome extension context;Language detection and matching - Implemented intelligent language analysis in AI prompt to ensure cover letter language matches job posting, handling edge cases with mixed-language content and maintaining professional tone across languages;API error handling and retry logic - Built comprehensive error handling with user-friendly status messages, automatic retry for failed requests, and graceful degradation when resume is missing;Monorepo architecture coordination - Configured Yarn Workspaces to manage shared types and dependencies between extension and backend, ensuring type safety across the full stack with consistent TypeScript configurations",
  "project.coverLetter.architecture": "Chrome Extension (Plasmo) - React-based popup UI with TypeScript, content scripts for DOM scraping, and background service worker;Backend API (NestJS) - Modular architecture with Controllers, Services, and DTOs for cover letter generation and document management;Database Layer (Prisma + PostgreSQL) - ORM for user profiles, resume storage, and authentication token management;AI Integration - DeepSeek API client with custom prompts, temperature tuning (0.7), and max token limits (1000) for optimal generation;Authentication System - Google OAuth 2.0 with Passport strategies, JWT token generation, and refresh token rotation;Docker Setup - Multi-container orchestration with Docker Compose for backend, database, and development environment",
  "project.coverLetter.technicalHighlights": "Content Script Injection - Dynamic script execution via chrome.scripting.executeScript() for isolated job details extraction;Message Passing Protocol - Chrome extension messaging between popup, content scripts, and background worker for cross-context communication;Type-Safe APIs - Full TypeScript coverage (92.8%) with shared interfaces between extension and backend for JobDetails, User, and API responses;Validation Pipeline - Class-validator decorators on DTOs (GenerateCoverLetterDto) ensuring data integrity before AI processing;Secure Storage - Chrome local storage for caching with encryption considerations for sensitive authentication tokens;Axios Instance Pattern - Centralized API service class with request/response interceptors for authentication and error handling;React Hooks Pattern - Custom hooks for authentication (useAuth), data fetching (useApi), and business logic (useCoverLetterGenerator);PDF Processing Pipeline - Multi-step document handling: upload → OCR (Tesseract) → text extraction (pdf-parse) → storage (Prisma)",
  "project.coverLetter.userFlow": "User installs Chrome extension and authenticates via Google OAuth;User uploads resume (PDF) which is processed via OCR and stored in database;User navigates to any job posting page (LinkedIn, Indeed, company website);User opens extension popup and optionally enters custom instructions;User clicks 'Generate Cover Letter' triggering job details extraction from current tab;Extension sends job HTML, extracted text, and user resume to backend API;DeepSeek AI analyzes job requirements and generates personalized cover letter;Generated letter appears in popup with copy and PDF download options;User can regenerate with different instructions or save for later use",

  "project.rlSuite.title": "Reinforcement Learning Suite - Multi-Environment AI Agent",
  "project.rlSuite.description": "Comprehensive reinforcement learning project implementing Q-Learning, SARSA, and Deep Q-Network (DQN) algorithms across multiple game environments including classic Gymnasium and Atari games.",
  "project.rlSuite.category": "AI/ML / Reinforcement Learning",
  "project.rlSuite.impact": "100% Python - Academic research project for Epitech MSc Pro",
  "project.rlSuite.fullDescription": "An advanced artificial intelligence project exploring multiple reinforcement learning algorithms applied to various game environments. The project demonstrates mastery of fundamental RL concepts (Q-Learning, SARSA) on classic Gymnasium environments, and extends to cutting-edge deep reinforcement learning with DQN implementation for Atari Pong. Built as part of the Epitech Master's program (T-AIA-902), this suite showcases the complete pipeline from algorithm implementation to model training, evaluation, and deployment with pre-trained models.",
  "project.rlSuite.features": "Q-Learning implementation for Frozen Lake 8x8 environment with configurable slipperiness;SARSA (State-Action-Reward-State-Action) algorithm for on-policy learning;Deep Q-Network (DQN) with experience replay and target network for Atari Pong;Cliff Walking environment with both Q-Learning and SARSA implementations for comparison;Taxi Driver environment with optimized Q-Learning for complex navigation;Model persistence with pickle (.pkl) and PyTorch (.pt) formats for reusability;Interactive play mode to test trained agents in real-time with human-readable rendering;TensorBoard integration for training visualization and performance metrics tracking;GPU acceleration with CUDA for faster DQN training on complex environments;Epsilon-greedy exploration strategy with decay for optimal exploitation-exploration balance;Modular codebase with separate training and testing scripts for each environment;Comprehensive documentation with detailed PDF report and presentation slides;Visual rendering with Pygame for human observation of agent behavior;Configurable hyperparameters (learning rate, discount factor, epsilon decay);Pre-trained models included for immediate testing and demonstration",
  "project.rlSuite.challenges": "Q-Table convergence optimization - Tuned learning rate (alpha) and discount factor (gamma) to achieve 95%+ success rate on Frozen Lake, balancing exploration vs exploitation with epsilon-greedy decay strategy;Credit assignment problem in sparse rewards - Implemented efficient Q-value updates for Cliff Walking where rewards only appear at goal state, using temporal difference learning to propagate value backwards;DQN stability and convergence - Solved notorious instability issues in deep RL by implementing experience replay buffer (storing 10K+ transitions) and separate target network updated every N episodes to break correlation in training data;High-dimensional state space handling - Designed convolutional neural network architecture for Atari Pong to process 84x84 pixel frames, using frame stacking (4 consecutive frames) to capture motion and velocity information;Catastrophic forgetting in neural networks - Mitigated through experience replay mechanism that samples random mini-batches from memory, preventing the network from forgetting previously learned strategies;Training time optimization - Leveraged CUDA GPU acceleration and parallel environment processing to reduce DQN training time from 40+ hours to under 8 hours on complex Atari games;Environment stochasticity - Handled non-deterministic Frozen Lake transitions (is_slippery mode) by training for longer episodes and averaging Q-values to learn robust policies;Reward shaping for faster learning - Analyzed and tuned reward structures in Taxi Driver to incentivize efficient passenger pickup/drop-off while penalizing unnecessary movements",
  "project.rlSuite.algorithms": "Q-Learning (Off-Policy TD Control) - Model-free algorithm learning optimal action-value function independently of agent's current policy;SARSA (On-Policy TD Control) - Updates Q-values based on action actually taken by current policy, more conservative than Q-Learning;Deep Q-Network (DQN) - Combines Q-Learning with deep neural networks for handling high-dimensional visual inputs from raw pixels;Experience Replay - Stores transitions in replay buffer and samples random mini-batches to break temporal correlations;Target Network - Separate network for generating Q-value targets, updated periodically to stabilize training;Epsilon-Greedy Exploration - Balances random exploration with greedy exploitation, with exponential decay schedule",
  "project.rlSuite.environments": "Frozen Lake 8x8 - Navigate icy grid world avoiding holes to reach goal, with optional stochastic transitions;Cliff Walking - Walk along cliff edge to reach goal while avoiding falling off (high negative reward);Taxi Driver - Multi-objective task: navigate grid, pick up passenger, drop at destination efficiently;Atari Pong - Classic arcade game requiring visual processing and temporal reasoning to beat opponent",
};


