export const messagesFr = {
  // Général
  "common.scroll": "Scroll",
  "common.available": "Disponible pour de nouveaux projets",
  "common.contactMe": "Me contacter",
  "common.viewProjects": "Voir mes projets",
  "common.discover": "Découvrir →",
  "common.sendMessage": "Envoyer le message",
  "common.name": "Nom",
  "common.email": "Email",
  "common.message": "Message",
  "common.sending": "Envoi en cours...",
  "common.contactInfo": "Informations de Contact",
  "common.professionalLinks": "Liens Professionnels",
  "common.downloadCv": "Télécharger mon CV",
  "common.githubProfile": "Profil GitHub",
  "common.linkedinProfile": "Profil LinkedIn",
  "common.location": "Localisation",
  "common.languages": "Langues",

  // Hero
  "hero.title": "Mustapha",
  "hero.subtitle": "Architecte Logiciel",
  "hero.description.part1": "Passionné par le développement full-stack et l'intelligence artificielle.",
  "hero.description.part2": "Je transforme des idées complexes en ",
  "hero.description.highlight": "produits innovants",

  // Resume header
  "resume.title": "Architecte Logiciel",
  "resume.location": "Toulouse, Occitanie, France",

  // À propos
  "about.title": "À propos de moi",
  "about.presentation": "Présentation",
  "about.presentation.p1": "Ingénieur logiciel passionné par le développement full-stack et l'intelligence artificielle. Je combine expertise technique et vision produit pour créer des solutions innovantes à fort impact.",
  "about.presentation.p2": "J'expérimente continuellement avec les technologies émergentes (RAG, blockchain, NLP) et transforme des idées complexes en produits concrets, de la conception au déploiement à grande échelle.",
  "about.location": "📍 Localisation",
  "about.location.value": "Toulouse, Occitanie, France",
  "about.languages": "🌍 Langues",
  "about.languages.items": "🇫🇷 Français (Natif);🇦🇪 Arabe (Natif);🇪🇸 Espagnol (Natif);🇪🇸 Catalan (Natif);🇬🇧 Anglais (Courant);🇮🇹 Italien (Conv.)",
  "about.education": "🎓 Formation",
  "about.education.items": "• Master Architecte Logiciel - EPITECH;• Bachelor DevOps - EPSI (Distinction);• Développeur Web - SIMPLON",

  // Contact
  "contact.title": "Me Contacter",
  "contact.alert": "Message envoyé! (Fonctionnalité à implémenter)",
  "contact.success": "Message envoyé avec succès! Je vous répondrai bientôt.",
  "contact.error": "Échec de l'envoi du message. Veuillez réessayer ou me contacter directement.",
  "contact.footer": "© 2025 Mustapha El Hachmi Mahti. Tous droits réservés.",

  // Sections
  "sections.experiences": "Expériences Professionnelles",
  "sections.projects": "Projets Réalisés",
  "sections.skills": "Compétences",

  // Labels
  "labels.stack": "Stack",

  // Experiences (aligned with resume)
  "exp.actual.title": "Développeur Full Stack",
  "exp.actual.company": "Groupe Actual",
  "exp.actual.location": "Toulouse",
  "exp.actual.period": "Septembre 2022 — Septembre 2025",
  "exp.actual.points": "Développement Web : Conception et développement d'applications React/TypeScript (50 000+ utilisateurs) complexes avec interfaces utilisateur avancées et gestion d'état optimisée;Applications Mobile : Développement cross-platform iOS/Android avec React Native/Expo (250000+ téléchargements);Architecture Backend : Conception de microservices NestJS avec APIs RESTful, gestion de données PostgreSQL/Redis;Performance & Scalabilité : Optimisation des performances web et mobile (+30% vitesse), mise en place de solutions de cache et monitoring temps réel;Data Engineering : Intégration BigQuery pour analytics métier et développement de pipelines de données haute disponibilité",
  "exp.actual.stack": "React, TypeScript, React Native, NestJS (NodeJS), MySQL, Redis, GCP",

  "exp.bizness.title": "Développeur Full Stack",
  "exp.bizness.company": "Groupe Bizness",
  "exp.bizness.location": "Toulouse",
  "exp.bizness.period": "Janvier 2022 — Août 2022",
  "exp.bizness.points": "Architecture Microservices : Développement d'architecture event-driven avec APIs d'agrégation multi-sources;Applications Temps Réel : Implémentation WebSockets et Server-Sent Events pour interfaces collaboratives;Base de Données et API : Développement d'APIs avec base de données SAP HANA",
  "exp.bizness.stack": "Node.js, WebSockets, SAP HANA",

  "exp.jump.title": "Développeur Full Stack",
  "exp.jump.company": "Société JUMP",
  "exp.jump.location": "Toulouse",
  "exp.jump.period": "Mai 2021 — Juillet 2021",
  "exp.jump.points": "Automatisation de tests E2E avec Selenium WebDriver, Cucumber JS et syntaxe Gherkin;Développement de commandes Slack personnalisées avec Bolt JS et NestJS;Création de workflows automatisés pour améliorer la productivité équipe",
  "exp.jump.stack": "Selenium, Cucumber JS, Bolt JS, NestJS",

  "exp.syntrix.title": "Cofondateur & CTO",
  "exp.syntrix.company": "Syntrix - Plateforme Compliance & Anti-Fraude",
  "exp.syntrix.location": "Remote",
  "exp.syntrix.period": "Juillet 2023",
  "exp.syntrix.points": "Plateforme SaaS compliance (3 clients grands comptes). Clients : Al Fardan Exchange et cabinets d'avocats.;Backend Microservices : Architecture NestJS avec modules FATCA/CRS et intégration CoreBanking;Applications Web : Interface NextJS (React) pour portail KYC automatisé et outils compliance;Systèmes Temps Réel : Module anti-fraude avec détection d'incidents et alerting automatique",
  "exp.syntrix.stack": "React (NextJS), NestJS (NodeJS), PostgreSQL, Redis, Kubernetes, Rabbitmq",

  // Projets
  "project.chat.title": "Application de Chat en Temps Réel",
  "project.chat.description": "Plateforme de chat full-stack prête pour la production avec authentification Google OAuth, messagerie directe, chats de groupe et partage de médias en temps réel.",
  "project.chat.category": "Full-Stack / Temps Réel",
  "project.chat.impact": "Monorepo avec 100+ fichiers, 95% TypeScript",
  "project.chat.fullDescription": "Une plateforme de messagerie de niveau entreprise sophistiquée construite avec des technologies modernes, comprenant l'authentification Google OAuth, la messagerie directe, les chats de groupe jusqu'à 50 membres et les capacités de partage de médias en temps réel. L'application utilise une architecture monorepo avec TypeScript (95% de la base de code), garantissant une sécurité de type complète sur toute la pile. Déployée avec conteneurisation Docker et automatisation Ansible pour une infrastructure prête pour la production.",
  "project.chat.features": "Authentification Google OAuth 2.0 avec gestion sécurisée des tokens JWT et tokens de rafraîchissement;Messagerie bidirectionnelle en temps réel via WebSockets avec Socket.IO et reconnexion automatique;Chats de groupe supportant jusqu'à 50 membres simultanés avec permissions basées sur les rôles;Partage de médias avec support glisser-déposer (images, GIFs) et génération d'URLs présignées;Indicateurs de saisie montrant les utilisateurs actifs en temps réel avec debouncing;Accusés de lecture de messages et suivi du statut de livraison entre plusieurs utilisateurs;Suivi du statut en ligne/hors ligne avec système de présence et horodatage de dernière connexion;Défilement infini pour l'historique des messages avec pagination basée sur curseur;Mises à jour optimistes de l'interface utilisateur pour un retour instantané et une expérience utilisateur réactive;Visionneuse de médias plein écran avec navigation au clavier et gestes tactiles;Design responsive mobile-first avec Tailwind CSS et composants shadcn/ui;Recherche et découverte d'utilisateurs avec filtrage en temps réel;Gestion de profil (bio, site web, avatar) avec optimisation d'images;Pagination des messages pour optimisation des performances sur de grandes conversations;Notifications en temps réel pour nouveaux messages et mentions",
  "project.chat.challenges": "Adaptateur d'authentification JWT WebSocket personnalisé - Construction d'un middleware sécurisé pour vérifier les tokens JWT lors de la poignée de main WebSocket, permettant l'authentification pour les connexions en temps réel;Stratégie de pagination basée sur curseur - Implémentation d'un chargement efficace de l'historique des messages utilisant des curseurs de base de données au lieu de la pagination par offset, améliorant les performances de 70% sur de grands ensembles de données;Architecture de stockage de médias évolutive - Conception et intégration de Cloudflare R2 (compatible S3) avec URLs présignées pour une livraison de médias sécurisée et évolutive sans goulot d'étranglement serveur;Synchronisation d'état en temps réel - Résolution du problème complexe de maintien de la cohérence de l'état des messages entre plusieurs clients connectés en utilisant les salles Socket.IO et la diffusion d'événements;Routage de messages basé sur les salles - Développement d'un système d'abonnement automatique des utilisateurs aux salles personnelles et de groupe lors de la connexion pour une livraison de messages ciblée sans surcharge;Suivi des accusés de lecture multi-utilisateurs - Implémentation d'un système efficace d'accusés de lecture suivant le statut de lecture individuel pour chaque utilisateur dans les chats de groupe sans problèmes de requêtes N+1;Gestion de connexion WebSocket - Construction d'une logique de reconnexion robuste avec backoff exponentiel et récupération d'état après interruptions réseau;Optimisation du schéma de base de données - Conception de modèles Prisma avec indexation stratégique sur les champs fréquemment interrogés (email, username, roomId, createdAt) pour des temps de requête inférieurs à 50ms",

  "project.syntrix.title": "Syntrix - Plateforme de Services Juridiques",
  "project.syntrix.description": "Plateforme full-stack moderne pour cabinets d'avocats avec gestion de clients, traitement sécurisé de documents et système de vérification KYC prévu pour la conformité réglementaire.",
  "project.syntrix.category": "Full-Stack / Legal Tech",
  "project.syntrix.impact": "Architecture monorepo avec 72,8% de couverture TypeScript",
  "project.syntrix.fullDescription": "Une plateforme de services juridiques de niveau entreprise conçue pour les cabinets d'avocats et les avocats indépendants afin de digitaliser leur pratique. Construite avec une architecture monorepo moderne utilisant Yarn Workspaces, la plateforme dispose d'une API backend NestJS et d'un frontend Next.js avec React 19. L'application est conteneurisée avec Docker et inclut des tests complets, des outils de qualité de code et suit les meilleures pratiques de l'industrie. Conçue avec la sécurité et la conformité à l'esprit, avec des capacités de vérification KYC/AML prévues pour répondre aux exigences réglementaires de l'industrie juridique.",
  "project.syntrix.features": "Architecture monorepo moderne avec Yarn Workspaces pour un partage de code efficace et une gestion des dépendances;Frontend Next.js 15 avec App Router, Server Components et React 19 pour des performances optimales;Backend NestJS 11 avec architecture modulaire, injection de dépendances et sécurité de type TypeScript;Design responsive mobile-first avec Tailwind CSS 4 pour une expérience fluide sur tous les appareils;Configuration Docker Compose pour des environnements de développement et de production cohérents;Menu CLI interactif pour un démarrage facile du projet et une sélection d'environnement;Formatage de code automatisé avec Prettier sur toute la base de code;Configuration ESLint complète avec règles spécifiques TypeScript et pratiques recommandées;Infrastructure de tests Jest pour tests unitaires, tests E2E et rapports de couverture de code;Rechargement à chaud et rafraîchissement rapide pour un retour instantané pendant le développement;Optimisation des images Next.js avec chargement paresseux automatique et images réactives;Gestion des variables d'environnement avec validation et sécurité de type;Configuration de déploiement prête pour la production pour Vercel et AWS;Intégration de la famille de polices Geist pour une typographie moderne et professionnelle;Fractionnement de code et tree shaking pour des tailles de bundle optimales",
  "project.syntrix.challenges": "Configuration monorepo - Architecture d'une configuration Yarn Workspaces évolutive gérant plusieurs applications (front/back) avec des dépendances partagées, réduisant la taille du bundle de 40% grâce à la déduplication des packages;Mode strict TypeScript sur toute la pile - Application d'une vérification de type stricte sur 72,8% de la base de code TypeScript, éliminant les erreurs de type à l'exécution et améliorant l'intellisense de l'IDE;Orchestration multi-services Docker - Conception de configuration Docker Compose gérant les services frontend, backend et base de données avec mise en réseau appropriée, persistance des volumes et vérifications de santé;Optimisation du workflow de développement - Construction d'un outil CLI interactif personnalisé avec Inquirer pour un démarrage de projet rationalisé, réduisant le changement de contexte et améliorant l'expérience développeur;Migration Next.js 15 App Router - Implémentation réussie de la nouvelle architecture App Router avec composants serveur et client, optimisant le chargement initial de page de 50%;Automatisation de la qualité du code - Intégration d'ESLint avec parser TypeScript et Prettier pour formatage automatisé, appliquant un style de code cohérent sur les contributions de l'équipe;Implémentation de stratégie de test - Établissement d'une infrastructure de test complète avec Jest supportant tests unitaires, tests d'intégration et tests E2E avec rapports de couverture;Optimisation de build - Configuration du compilateur SWC pour des builds plus rapides (20x plus rapide que Babel) et optimisation des bundles de production avec tree shaking",
  "project.syntrix.plannedFeatures": "Module KYC/AML - Système complet de vérification Know Your Customer avec téléchargement de documents, vérification OCR, validation d'identité et contrôle de conformité pour exigences réglementaires;Portail Client - Tableau de bord sécurisé pour que les clients puissent consulter l'état des dossiers, télécharger des documents et communiquer avec les avocats;Système de Gestion de Documents - Stockage sécurisé centralisé avec contrôle de version, permissions d'accès et piste d'audit pour documents juridiques;Planification de Rendez-vous - Intégration calendrier avec rappels automatisés et détection de conflits pour réunions clients;Facturation & Facturation - Suivi du temps, gestion des dépenses et génération automatisée de factures avec traitement des paiements;Gestion de Dossiers - Système complet pour suivre les dossiers, échéances, audiences et documents associés avec automatisation du workflow;Messagerie Sécurisée - Communication chiffrée de bout en bout entre avocats et clients avec accusés de lecture et partage de fichiers;Contrôle d'Accès Basé sur les Rôles - Système de permissions granulaires pour associés, collaborateurs, parajuristes et clients;Intégration de Criblage AML - Criblage automatisé contre les listes de sanctions internationales et bases de données PEP;Conformité RGPD/Confidentialité - Fonctionnalités de protection des données incluant export de données, suppression, gestion du consentement et journaux d'audit;Support Multi-langues - Internationalisation pour servir des clients dans plusieurs juridictions;Tableau de Bord Analytique - Business intelligence avec statistiques de dossiers, suivi des revenus et métriques de performance",

  "project.coverLetter.title": "Générateur de Lettres de Motivation IA - Extension Chrome",
  "project.coverLetter.description": "Extension Chrome intelligente qui génère automatiquement des lettres de motivation personnalisées en analysant les offres d'emploi en temps réel et en les associant aux CV des utilisateurs grâce à une technologie IA avancée.",
  "project.coverLetter.category": "Full-Stack / Extension Navigateur / IA",
  "project.coverLetter.impact": "Monorepo avec 92,8% TypeScript - Extension navigateur en production",
  "project.coverLetter.fullDescription": "Une extension Chrome sophistiquée propulsée par l'IA qui révolutionne le processus de candidature en générant automatiquement des lettres de motivation sur mesure. L'extension extrait intelligemment le contenu des offres d'emploi depuis n'importe quelle page carrières, analyse les exigences avec l'IA et crée des lettres de motivation personnalisées parfaitement alignées avec le CV du candidat. Construite avec une architecture monorepo comprenant une interface d'extension Chrome en React et une API backend robuste en NestJS, l'application exploite DeepSeek AI pour le traitement du langage naturel et supporte la génération multilingue, s'adaptant automatiquement à la langue de l'offre d'emploi.",
  "project.coverLetter.features": "Extraction en temps réel des offres d'emploi depuis n'importe quel site carrières via scripts de contenu et manipulation DOM;Analyse HTML intelligente pour extraire titre du poste, entreprise, description, exigences et qualifications;Génération de lettres de motivation propulsée par l'IA utilisant DeepSeek LLM avec prompts et instructions personnalisables;Détection et correspondance automatique de la langue - génère des lettres dans la même langue que l'offre d'emploi;Authentification Google OAuth 2.0 avec gestion sécurisée des tokens JWT et rotation des tokens de rafraîchissement;Téléchargement de CV et traitement OCR avec Tesseract.js pour extraire le texte des documents PDF;Capacités d'analyse PDF pour lire les CV existants et extraire le contenu structuré;Système d'instructions personnalisées permettant aux utilisateurs d'accentuer des compétences spécifiques ou d'ajuster ton/longueur;Fonctionnalité de copie en un clic vers le presse-papiers pour soumission instantanée de candidature;Fonction d'export PDF pour télécharger les lettres de motivation générées en format professionnel;Interface popup d'extension Chrome avec design glassmorphique moderne et arrière-plans en dégradé;Mise en cache dans le stockage local de la dernière lettre générée pour éviter les appels API inutiles;Navigation par onglets (Générer, Profil, Paramètres) avec transitions fluides;Messages de statut et états de chargement avec indicateurs de progression en temps réel;Stockage et gestion du contenu des CV dans base de données PostgreSQL avec Prisma;API backend RESTful avec validation appropriée utilisant class-validator et class-transformer;Conteneurisation Docker pour environnements de développement et production cohérents;Intercepteurs Axios pour injection automatique des tokens d'authentification et gestion des erreurs;Permissions d'extension Chrome pour onglets, stockage, scripts et accès à l'onglet actif;Script d'arrière-plan pour extraction persistante des détails d'emploi à travers les onglets",
  "project.coverLetter.challenges": "Scraping de contenu cross-origin - Implémentation de scripts de contenu d'extension Chrome avec permissions appropriées (host_permissions pour https://*/*) pour injecter des scripts dans les pages d'offres d'emploi et extraire des données structurées depuis diverses mises en page HTML sur différentes plateformes carrières;Analyse de sites web dynamiques - Construction d'algorithmes robustes de parcours DOM pour gérer des structures HTML variées de différentes entreprises (LinkedIn, Indeed, Greenhouse, Lever, etc.), utilisant plusieurs sélecteurs de secours pour assurer une extraction fiable des détails d'emploi;Ingénierie de prompts IA - Création de prompts sophistiqués multi-parties qui analysent à la fois HTML brut et contenu textuel extrait (jusqu'à 120K caractères), instruisant DeepSeek AI pour générer des lettres de motivation authentiques sans inventer d'expérience, maintenant des contraintes de longueur de 250-350 mots;Précision OCR des CV - Intégration de Tesseract.js pour reconnaissance optique de caractères sur CV PDF scannés, implémentation de techniques de prétraitement pour améliorer la précision d'extraction de texte depuis divers formats et mises en page de documents;Flux d'authentification d'extension Chrome - Résolution du défi complexe d'authentification en implémentant le stockage sécurisé de tokens JWT dans chrome.storage.local, avec rafraîchissement automatique de token avant les appels API et gestion transparente des redirections Google OAuth;Génération PDF dans le navigateur - Implémentation de création PDF côté client utilisant la bibliothèque jsPDF, formatant le contenu de lettre de motivation avec marges, polices et style professionnel appropriés sans dépendance backend;Gestion d'état d'extension - Conception de pattern de hooks React (useCoverLetterGenerator, useAuth, useApi) pour gérer des workflows asynchrones complexes incluant requêtes d'onglets, passage de messages et appels API dans le contexte d'extension Chrome;Détection et correspondance de langue - Implémentation d'analyse de langue intelligente dans le prompt IA pour assurer que la langue de la lettre de motivation correspond à l'offre d'emploi, gérant les cas limites avec contenu multilingue et maintenant un ton professionnel dans toutes les langues;Gestion d'erreurs API et logique de retry - Construction de gestion d'erreurs complète avec messages de statut conviviaux, retry automatique pour requêtes échouées et dégradation gracieuse quand le CV est manquant;Coordination d'architecture monorepo - Configuration de Yarn Workspaces pour gérer les types et dépendances partagés entre extension et backend, assurant la sécurité de type sur toute la pile avec configurations TypeScript cohérentes",
  "project.coverLetter.architecture": "Extension Chrome (Plasmo) - Interface utilisateur popup basée sur React avec TypeScript, scripts de contenu pour scraping DOM et service worker d'arrière-plan;API Backend (NestJS) - Architecture modulaire avec Controllers, Services et DTOs pour génération de lettres de motivation et gestion de documents;Couche Base de Données (Prisma + PostgreSQL) - ORM pour profils utilisateurs, stockage de CV et gestion de tokens d'authentification;Intégration IA - Client API DeepSeek avec prompts personnalisés, ajustement de température (0.7) et limites de tokens max (1000) pour génération optimale;Système d'Authentification - Google OAuth 2.0 avec stratégies Passport, génération de tokens JWT et rotation des tokens de rafraîchissement;Configuration Docker - Orchestration multi-conteneurs avec Docker Compose pour backend, base de données et environnement de développement",
  "project.coverLetter.technicalHighlights": "Injection de Script de Contenu - Exécution dynamique de script via chrome.scripting.executeScript() pour extraction isolée des détails d'emploi;Protocole de Passage de Messages - Messagerie d'extension Chrome entre popup, scripts de contenu et worker d'arrière-plan pour communication inter-contextes;APIs Type-Safe - Couverture TypeScript complète (92,8%) avec interfaces partagées entre extension et backend pour JobDetails, User et réponses API;Pipeline de Validation - Décorateurs Class-validator sur DTOs (GenerateCoverLetterDto) assurant l'intégrité des données avant traitement IA;Stockage Sécurisé - Stockage local Chrome pour mise en cache avec considérations de chiffrement pour tokens d'authentification sensibles;Pattern Instance Axios - Classe de service API centralisée avec intercepteurs requête/réponse pour authentification et gestion d'erreurs;Pattern Hooks React - Hooks personnalisés pour authentification (useAuth), récupération de données (useApi) et logique métier (useCoverLetterGenerator);Pipeline de Traitement PDF - Gestion de documents multi-étapes : téléchargement → OCR (Tesseract) → extraction de texte (pdf-parse) → stockage (Prisma)",
  "project.coverLetter.userFlow": "L'utilisateur installe l'extension Chrome et s'authentifie via Google OAuth;L'utilisateur télécharge son CV (PDF) qui est traité via OCR et stocké dans la base de données;L'utilisateur navigue vers n'importe quelle page d'offre d'emploi (LinkedIn, Indeed, site web d'entreprise);L'utilisateur ouvre le popup d'extension et entre optionnellement des instructions personnalisées;L'utilisateur clique sur 'Générer Lettre de Motivation' déclenchant l'extraction des détails d'emploi depuis l'onglet actuel;L'extension envoie le HTML de l'emploi, le texte extrait et le CV de l'utilisateur à l'API backend;DeepSeek AI analyse les exigences de l'emploi et génère une lettre de motivation personnalisée;La lettre générée apparaît dans le popup avec options de copie et téléchargement PDF;L'utilisateur peut régénérer avec différentes instructions ou sauvegarder pour utilisation ultérieure",

  "project.rlSuite.title": "Suite d'Apprentissage par Renforcement - Agent IA Multi-Environnements",
  "project.rlSuite.description": "Projet complet d'apprentissage par renforcement implémentant les algorithmes Q-Learning, SARSA et Deep Q-Network (DQN) sur plusieurs environnements de jeu incluant Gymnasium classique et jeux Atari.",
  "project.rlSuite.category": "IA/ML / Apprentissage par Renforcement",
  "project.rlSuite.impact": "100% Python - Projet de recherche académique pour Epitech MSc Pro",
  "project.rlSuite.fullDescription": "Un projet d'intelligence artificielle avancé explorant plusieurs algorithmes d'apprentissage par renforcement appliqués à divers environnements de jeu. Le projet démontre la maîtrise des concepts fondamentaux du RL (Q-Learning, SARSA) sur les environnements Gymnasium classiques, et s'étend à l'apprentissage par renforcement profond de pointe avec l'implémentation DQN pour Atari Pong. Réalisé dans le cadre du programme Master d'Epitech (T-AIA-902), cette suite présente le pipeline complet depuis l'implémentation des algorithmes jusqu'à l'entraînement, l'évaluation et le déploiement des modèles avec des modèles pré-entraînés.",
  "project.rlSuite.features": "Implémentation Q-Learning pour l'environnement Frozen Lake 8x8 avec glissance configurable;Algorithme SARSA (State-Action-Reward-State-Action) pour l'apprentissage on-policy;Deep Q-Network (DQN) avec experience replay et target network pour Atari Pong;Environnement Cliff Walking avec implémentations Q-Learning et SARSA pour comparaison;Environnement Taxi Driver avec Q-Learning optimisé pour navigation complexe;Persistance des modèles avec formats pickle (.pkl) et PyTorch (.pt) pour réutilisabilité;Mode de jeu interactif pour tester les agents entraînés en temps réel avec rendu lisible;Intégration TensorBoard pour visualisation de l'entraînement et suivi des métriques de performance;Accélération GPU avec CUDA pour entraînement DQN plus rapide sur environnements complexes;Stratégie d'exploration epsilon-greedy avec décroissance pour équilibre exploitation-exploration optimal;Base de code modulaire avec scripts d'entraînement et de test séparés pour chaque environnement;Documentation complète avec rapport PDF détaillé et slides de présentation;Rendu visuel avec Pygame pour observation humaine du comportement de l'agent;Hyperparamètres configurables (taux d'apprentissage, facteur de réduction, décroissance epsilon);Modèles pré-entraînés inclus pour test et démonstration immédiats",
  "project.rlSuite.challenges": "Optimisation convergence Q-Table - Ajustement du taux d'apprentissage (alpha) et facteur de réduction (gamma) pour atteindre 95%+ de taux de succès sur Frozen Lake, équilibrant exploration vs exploitation avec stratégie de décroissance epsilon-greedy;Problème d'attribution de crédit dans récompenses éparses - Implémentation de mises à jour efficaces des Q-values pour Cliff Walking où les récompenses n'apparaissent qu'à l'état objectif, utilisant l'apprentissage par différence temporelle pour propager la valeur en arrière;Stabilité et convergence DQN - Résolution des problèmes notoires d'instabilité du RL profond en implémentant un buffer d'experience replay (stockant 10K+ transitions) et réseau cible séparé mis à jour tous les N épisodes pour briser la corrélation dans les données d'entraînement;Gestion espace d'états haute dimension - Conception d'architecture réseau neuronal convolutif pour Atari Pong traitant des frames de 84x84 pixels, utilisant l'empilement de frames (4 frames consécutives) pour capturer mouvement et vélocité;Oubli catastrophique dans réseaux neuronaux - Atténué par mécanisme d'experience replay échantillonnant des mini-batchs aléatoires de la mémoire, empêchant le réseau d'oublier les stratégies apprises précédemment;Optimisation temps d'entraînement - Utilisation de l'accélération GPU CUDA et traitement parallèle d'environnements pour réduire le temps d'entraînement DQN de 40+ heures à moins de 8 heures sur jeux Atari complexes;Stochasticité de l'environnement - Gestion des transitions non déterministes de Frozen Lake (mode is_slippery) en s'entraînant pour plus d'épisodes et en moyennant les Q-values pour apprendre des politiques robustes;Façonnage de récompense pour apprentissage plus rapide - Analyse et ajustement des structures de récompense dans Taxi Driver pour inciter au ramassage/dépôt efficace de passagers tout en pénalisant les mouvements inutiles",
  "project.rlSuite.algorithms": "Q-Learning (Contrôle TD Off-Policy) - Algorithme sans modèle apprenant la fonction valeur-action optimale indépendamment de la politique actuelle de l'agent;SARSA (Contrôle TD On-Policy) - Met à jour les Q-values basées sur l'action réellement prise par la politique actuelle, plus conservateur que Q-Learning;Deep Q-Network (DQN) - Combine Q-Learning avec réseaux neuronaux profonds pour gérer les entrées visuelles haute dimension depuis pixels bruts;Experience Replay - Stocke les transitions dans un buffer de replay et échantillonne des mini-batchs aléatoires pour briser les corrélations temporelles;Target Network - Réseau séparé pour générer les cibles de Q-value, mis à jour périodiquement pour stabiliser l'entraînement;Exploration Epsilon-Greedy - Équilibre exploration aléatoire avec exploitation gloutonne, avec calendrier de décroissance exponentielle",
  "project.rlSuite.environments": "Frozen Lake 8x8 - Naviguer dans un monde grille glacé en évitant les trous pour atteindre l'objectif, avec transitions stochastiques optionnelles;Cliff Walking - Marcher le long du bord de falaise pour atteindre l'objectif tout en évitant de tomber (récompense négative élevée);Taxi Driver - Tâche multi-objectifs : naviguer dans la grille, ramasser passager, déposer à destination efficacement;Atari Pong - Jeu d'arcade classique nécessitant traitement visuel et raisonnement temporel pour battre l'adversaire",
};


