export const messagesFr = {
  // Général
  "common.scroll": "Scroll",
  "common.available": "Disponible pour de nouveaux projets",
  "common.contactMe": "Me contacter",
  "common.viewProjects": "Voir mes projets",
  "common.viewDetails": "Voir les détails",
  "common.discover": "Découvrir →",
  "common.sendMessage": "Envoyer le message",
  "common.name": "Nom",
  "common.email": "Email",
  "common.message": "Message",
  "common.sending": "Envoi en cours...",
  "common.contactInfo": "Informations de Contact",
  "common.professionalLinks": "Liens Professionnels",
  "common.downloadCv": "Télécharger mon CV",
  "common.githubProfile": "Profil GitHub",
  "common.linkedinProfile": "Profil LinkedIn",
  "common.location": "Localisation",
  "common.languages": "Langues",
  "common.liveDemo": "Démo",

  // Tooltips
  "tooltip.resume": "Voir le CV",
  "tooltip.welcomeBot": "Guide du Portfolio",
  "tooltip.languageToggle": "Changer de Langue",
  "tooltip.howItsMade": "Comment c'est fait",

  // Hero
  "hero.title": "Mustapha",
  "hero.subtitle": "Ingénieur IA & Architecte RAG",
  "hero.description.part1":
    "Spécialisé dans les systèmes IA, architectures RAG et Knowledge Graphs.",
  "hero.description.part2": "Je transforme les documents en ",
  "hero.description.highlight": "connaissance intelligente et interrogeable",

  // Resume header
  "resume.title": "Ingénieur IA & Architecte RAG",
  "resume.location": "Toulouse, Occitanie, France",

  // À propos
  "about.title": "À propos de moi",
  "about.presentation": "Présentation",
  "about.presentation.p1":
    "Ingénieur IA spécialisé dans les systèmes RAG, Knowledge Graphs et traitement intelligent de documents. J'architecte des solutions IA production-ready qui transforment les données non structurées en connaissances exploitables.",
  "about.presentation.p2":
    "Je combine expertise approfondie en Graph RAG, NLP, bases de données vectorielles et développement full-stack pour construire des systèmes intelligents qui extraient des insights de données complexes. Passionné par repousser les limites du possible avec les LLMs et knowledge graphs.",
  "about.location.title": "Localisation",
  "about.location.value": "Toulouse, Occitanie, France",
  "about.languages.title": "Langues",
  "about.languages.french": "Français (Natif)",
  "about.languages.arabic": "Arabe (Natif)",
  "about.languages.spanish": "Espagnol (Natif)",
  "about.languages.catalan": "Catalan (Natif)",
  "about.languages.english": "Anglais (Courant)",
  "about.languages.italian": "Italien (Conv.)",
  "about.education.title": "Formation",
  "about.education.master.degree": "Master Architecte Logiciel",
  "about.education.master.school": "École Informatique EPITECH",
  "about.education.master.location": "Toulouse",
  "about.education.master.period": "2023 — 2025",
  "about.education.bachelor.degree":
    "Bachelor Concepteur Développeur d'Applications DevOps",
  "about.education.bachelor.school": "EPSI",
  "about.education.bachelor.location": "Toulouse",
  "about.education.bachelor.period": "2022 — 2023",
  "about.education.bachelor.distinction": "Avec distinction du jury",
  "about.education.bac2.degree": "Développeur Web et Web Mobile",
  "about.education.bac2.school": "SIMPLON",
  "about.education.bac2.location": "Toulouse",
  "about.education.bac2.period": "2021 — 2022",
  "about.education.bac.degree": "Bac Sciences et Technologie",
  "about.education.bac.school": "IES Salvador Espriu",
  "about.education.bac.location": "Girona, Espagne",
  "about.education.bac.period": "2018 — 2019",

  // Contact
  "contact.title": "Me Contacter",
  "contact.alert": "Message envoyé! (Fonctionnalité à implémenter)",
  "contact.success": "Message envoyé avec succès! Je vous répondrai bientôt.",
  "contact.error":
    "Échec de l'envoi du message. Veuillez réessayer ou me contacter directement.",
  "contact.footer": "© 2025 Mustapha El Hachmi Mahti. Tous droits réservés.",

  // Sections
  "sections.experiences": "Expériences Professionnelles",
  "sections.projects": "Projets Réalisés",
  "sections.skills": "Compétences",

  // Labels
  "labels.stack": "Stack",

  // How It's Made Modal
  "howItsMade.title": "Comment Ce Portfolio A Été Créé",
  "howItsMade.subtitle": "Les coulisses de ce portfolio interactif",
  "howItsMade.overview.title": "Aperçu",
  "howItsMade.overview.description":
    "Ce portfolio a été construit de zéro en utilisant des technologies web modernes pour créer une expérience fluide et interactive. Chaque animation, transition et interaction a été soigneusement conçue pour mettre en valeur à la fois les compétences techniques et l'attention aux détails.",
  "howItsMade.techStack.title": "Stack Technique",
  "howItsMade.techStack.items":
    "Next.js 15 - Framework React avec App Router et Server Components;TypeScript - Développement type-safe sur toute la base de code;Tailwind CSS - Framework CSS utilitaire pour un styling rapide;Framer Motion - Bibliothèque d'animation prête pour la production;GSAP & ScrollTrigger - Animations avancées basées sur le scroll et effets parallaxe;Lenis - Bibliothèque de scroll fluide pour une expérience améliorée;React Hook Form - Gestion performante de formulaires avec validation;i18n - Support d'internationalisation pour anglais et français",
  "howItsMade.animations.title": "Techniques d'Animation",
  "howItsMade.animations.items":
    "Animations déclenchées au scroll avec GSAP ScrollTrigger pour révélation dynamique du contenu;Effets parallaxe sur la section hero et titres de projets pour perception de profondeur;Animations en cascade sur les cartes de projets pour apparition séquentielle;Effets d'inclinaison 3D sur les cartes de projets avec composant TiltCard personnalisé;Transitions de page fluides avec variants Framer Motion;Micro-interactions sur boutons et liens avec états hover/tap;Animation flottante de badge dans la section hero avec mouvement continu;Animations basées sur timeline pour les cartes d'expérience;Effets de curseur magnétique sur éléments interactifs",
  "howItsMade.features.title": "Fonctionnalités Clés",
  "howItsMade.features.items":
    "Design entièrement responsive fonctionnant parfaitement sur mobile, tablette et desktop;Interface sombre avec effets glassmorphisme et dégradés subtils;Support bilingue avec changement de langue instantané (EN/FR);Pages de projets dynamiques avec études de cas détaillées;Scroll fluide avec Lenis pour une expérience utilisateur améliorée;Performance optimisée avec composant Next.js Image et lazy loading;SEO-friendly avec balises meta appropriées et protocole Open Graph;Interface accessible avec labels ARIA appropriés et navigation clavier;Routage type-safe avec Next.js App Router;Architecture basée sur composants pour maintenabilité",
  "howItsMade.performance.title": "Performance & Optimisation",
  "howItsMade.performance.description":
    "Construit avec la performance à l'esprit, ce portfolio utilise les server components Next.js pour des chargements de page initiaux rapides, le code splitting pour des tailles de bundle optimales, et des images optimisées avec lazy loading automatique. Les animations sont accélérées par GPU en utilisant les propriétés transform et opacity pour maintenir 60fps.",
  "howItsMade.viewSource": "Voir le Code Source sur GitHub",

  // Experiences (aligned with resume)
  "exp.actual.title": "Développeur Full Stack",
  "exp.actual.company": "Groupe Actual",
  "exp.actual.location": "Toulouse",
  "exp.actual.period": "Septembre 2022 — Septembre 2025",
  "exp.actual.points":
    "Développement Web : Conception et développement d'applications React/TypeScript (50 000+ utilisateurs) complexes avec interfaces utilisateur avancées et gestion d'état optimisée;Applications Mobile : Développement cross-platform iOS/Android avec React Native/Expo (250000+ téléchargements);Architecture Backend : Conception de microservices NestJS avec APIs RESTful, gestion de données PostgreSQL/Redis;Performance & Scalabilité : Optimisation des performances web et mobile (+30% vitesse), mise en place de solutions de cache et monitoring temps réel;Data Engineering : Intégration BigQuery pour analytics métier et développement de pipelines de données haute disponibilité",
  "exp.actual.stack":
    "React, TypeScript, React Native, NestJS (NodeJS), MySQL, Redis, GCP",

  "exp.bizness.title": "Développeur Full Stack",
  "exp.bizness.company": "Groupe Bizness",
  "exp.bizness.location": "Toulouse",
  "exp.bizness.period": "Janvier 2022 — Août 2022",
  "exp.bizness.points":
    "Architecture Microservices : Développement d'architecture event-driven avec APIs d'agrégation multi-sources;Applications Temps Réel : Implémentation WebSockets et Server-Sent Events pour interfaces collaboratives;Base de Données et API : Développement d'APIs avec base de données SAP HANA",
  "exp.bizness.stack": "Node.js, WebSockets, SAP HANA",

  "exp.jump.title": "Développeur Full Stack",
  "exp.jump.company": "Société JUMP",
  "exp.jump.location": "Toulouse",
  "exp.jump.period": "Mai 2021 — Juillet 2021",
  "exp.jump.points":
    "Automatisation de tests E2E avec Selenium WebDriver, Cucumber JS et syntaxe Gherkin;Développement de commandes Slack personnalisées avec Bolt JS et NestJS;Création de workflows automatisés pour améliorer la productivité équipe",
  "exp.jump.stack": "Selenium, Cucumber JS, Bolt JS, NestJS",

  "exp.syntrix.title": "Cofondateur & CTO",
  "exp.syntrix.company": "Syntrix - Plateforme Compliance & Anti-Fraude",
  "exp.syntrix.location": "Remote",
  "exp.syntrix.period": "Juillet 2023",
  "exp.syntrix.points":
    "Plateforme SaaS compliance (3 clients grands comptes). Clients : Al Fardan Exchange et cabinets d'avocats.;Backend Microservices : Architecture NestJS avec modules FATCA/CRS et intégration CoreBanking;Applications Web : Interface NextJS (React) pour portail KYC automatisé et outils compliance;Systèmes Temps Réel : Module anti-fraude avec détection d'incidents et alerting automatique",
  "exp.syntrix.stack":
    "React (NextJS), NestJS (NodeJS), PostgreSQL, Redis, Kubernetes, Rabbitmq",

  // Projets
  "project.archeon.title": "Archeon - Second Brain Propulsé par l'IA",
  "project.archeon.description":
    "Plateforme full-stack d'intelligence documentaire utilisant Graph RAG, Knowledge Graphs et recherche sémantique pour transformer les documents en base de connaissances intelligente et interrogeable.",
  "project.archeon.category": "IA / Graph RAG / Knowledge Graphs",
  "project.archeon.impact":
    "Plateforme IA production-ready avec architecture microservices",
  "project.archeon.fullDescription":
    "Archeon est une plateforme sophistiquée de gestion de documents et de connaissances propulsée par l'IA qui aide les utilisateurs à organiser, rechercher et extraire des insights de leurs documents. Construite avec des technologies modernes et alimentée par Graph RAG avancé (Retrieval-Augmented Generation), Archeon transforme votre bibliothèque de documents en un second cerveau intelligent. La plateforme dispose d'une architecture microservices distribuée avec NestJS (Gate) et FastAPI (Scribe), Neo4j pour les knowledge graphs via Graphiti, et pgvector pour les embeddings sémantiques.",
  "project.archeon.features":
    "Graph RAG avec Neo4j + Graphiti pour extraction d'entités et mapping de relations;Recherche hybride combinant retrieval sémantique, par mots-clés et basé sur graphe;Q&A propulsé par l'IA utilisant LLMs (LLaMA 3.1 70B via Fireworks AI) pour interrogation intelligente de documents;Classification automatique de documents et génération de métadonnées avec IA;Traitement de documents en temps réel avec workers Celery et pipelines async;Embeddings vectoriels avec Nomic Embed (768 dimensions) stockés dans pgvector;Traitement OCR avec Tesseract pour extraction de texte depuis PDFs et images;Disponibilité multi-plateforme avec app mobile React Native et dashboard web Next.js;Authentification JWT avec rate limiting et sécurité production-ready;Architecture microservices avec Gate (NestJS) et Scribe (FastAPI);Intégration Cloudflare R2 pour stockage de documents évolutif;Environnement de développement Docker avec hot reload pour développement rapide;Stack d'observabilité complète avec Prometheus, Grafana, Loki et Promtail pour métriques et logs;Dashboards de monitoring en temps réel avec visualisations Grafana préconfigurées pour tous les services",
  "project.archeon.challenges":
    "Implémentation Graph RAG - Intégration du framework Graphiti avec Neo4j pour construire des knowledge graphs depuis les documents, implémentant extraction d'entités, stockage de faits et mapping de relations pour une récupération de contexte supérieure au RAG traditionnel;Architecture de recherche hybride - Conception de recherche multi-modale combinant embeddings sémantiques pgvector, recherche par mots-clés Elasticsearch et traversée de graphe Neo4j, avec fusion intelligente des résultats et reranking pour pertinence optimale;Pipeline de traitement de documents async - Construction d'un système de workers Celery évolutif gérant OCR, classification IA, génération d'embeddings et ingestion de graphe avec gestion d'erreurs appropriée, logique de retry et suivi de statut;Intégration LLM et prompt engineering - Implémentation de l'intégration Fireworks AI avec LLaMA 3.1 70B, création de prompts pour classification de documents, génération Q&A et extraction d'entités tout en gérant limites de tokens et qualité de réponse;Communication microservices - Architecture de communication sécurisée service-à-service entre Gate (NestJS) et Scribe (FastAPI) utilisant clés API internes, avec propagation d'erreurs et monitoring de santé appropriés;Optimisation base de données vectorielle - Ajustement des index pgvector et stratégies de requête pour recherche sémantique sub-100ms sur des milliers d'embeddings de documents;Conception de schéma knowledge graph - Modélisation du schéma Neo4j pour entités, faits et relations permettant requêtes de graphe complexes tout en maintenant performance d'ingestion;Sync multi-plateforme - Assurance de cohérence des données entre app mobile React Native, web Next.js et services backend avec mises à jour en temps réel et support offline",
  "project.archeon.architecture":
    "Couche Frontend - Dashboard web Next.js et app mobile React Native/Expo pour accès multi-plateforme;API Gate (NestJS) - Authentification, autorisation, rate limiting, CRUD documents, orchestration de recherche et gestion utilisateurs;API Scribe (FastAPI) - Recherche knowledge graph, génération Q&A, gestion d'entités et endpoints de traitement IA;Workers Scribe (Celery) - Traitement async de documents incluant OCR, classification IA, génération d'embeddings et ingestion de graphe;Couche Data - PostgreSQL avec pgvector pour données relationnelles et embeddings, Neo4j avec Graphiti pour knowledge graphs, Redis pour cache et files de tâches, Cloudflare R2 pour stockage de documents",
  "project.archeon.devNotice.title": "Projet en Développement",
  "project.archeon.devNotice.description":
    "Archeon est actuellement en développement actif et n'est pas encore disponible sur l'App Store ou Google Play. L'application mobile et la plateforme sont en cours de perfectionnement pour offrir la meilleure expérience possible. Restez à l'écoute pour le lancement officiel !",
  "project.archeon.devNotice.notAvailable":
    "pas encore disponible sur l'App Store ou Google Play",
  "project.archeon.devNotice.activeDev": "Développement Actif",
  "project.archeon.devNotice.comingSoon": "Bientôt sur iOS et Android",
  "project.archeon.beta.title": "Rejoignez le Programme Bêta",
  "project.archeon.beta.description":
    "Vous voulez un accès anticipé à Archeon ? Nous lançons une version bêta fermée dans les prochaines semaines ! Si vous êtes intéressé par les tests de l'application et les retours, contactez-nous et nous vous ajouterons au programme bêta.",
  "project.archeon.beta.button": "Rejoindre la Bêta",
  "project.archeon.gallery.title": "Captures d'Écran",
  "project.archeon.gallery.description":
    "Découvrez l'expérience Archeon à travers ces captures d'écran de l'application mobile, diagrammes d'architecture et tableaux de bord de monitoring.",

  "project.chat.title": "Application de Chat en Temps Réel",
  "project.chat.description":
    "Plateforme de chat full-stack prête pour la production avec authentification Google OAuth, messagerie directe, chats de groupe et partage de médias en temps réel.",
  "project.chat.category": "Full-Stack / Temps Réel",
  "project.chat.impact": "Monorepo avec 100+ fichiers, 95% TypeScript",
  "project.chat.fullDescription":
    "Une plateforme de messagerie de niveau entreprise sophistiquée construite avec des technologies modernes, comprenant l'authentification Google OAuth, la messagerie directe, les chats de groupe jusqu'à 50 membres et les capacités de partage de médias en temps réel. L'application utilise une architecture monorepo avec TypeScript (95% de la base de code), garantissant une sécurité de type complète sur toute la pile. Déployée avec conteneurisation Docker et automatisation Ansible pour une infrastructure prête pour la production.",
  "project.chat.features":
    "Authentification Google OAuth 2.0 avec gestion sécurisée des tokens JWT et tokens de rafraîchissement;Messagerie bidirectionnelle en temps réel via WebSockets avec Socket.IO et reconnexion automatique;Chats de groupe supportant jusqu'à 50 membres simultanés avec permissions basées sur les rôles;Partage de médias avec support glisser-déposer (images, GIFs) et génération d'URLs présignées;Indicateurs de saisie montrant les utilisateurs actifs en temps réel avec debouncing;Accusés de lecture de messages et suivi du statut de livraison entre plusieurs utilisateurs;Suivi du statut en ligne/hors ligne avec système de présence et horodatage de dernière connexion;Défilement infini pour l'historique des messages avec pagination basée sur curseur;Mises à jour optimistes de l'interface utilisateur pour un retour instantané et une expérience utilisateur réactive;Visionneuse de médias plein écran avec navigation au clavier et gestes tactiles;Design responsive mobile-first avec Tailwind CSS et composants shadcn/ui;Recherche et découverte d'utilisateurs avec filtrage en temps réel;Gestion de profil (bio, site web, avatar) avec optimisation d'images;Pagination des messages pour optimisation des performances sur de grandes conversations;Notifications en temps réel pour nouveaux messages et mentions",
  "project.chat.challenges":
    "Adaptateur d'authentification JWT WebSocket personnalisé - Construction d'un middleware sécurisé pour vérifier les tokens JWT lors de la poignée de main WebSocket, permettant l'authentification pour les connexions en temps réel;Stratégie de pagination basée sur curseur - Implémentation d'un chargement efficace de l'historique des messages utilisant des curseurs de base de données au lieu de la pagination par offset, améliorant les performances de 70% sur de grands ensembles de données;Architecture de stockage de médias évolutive - Conception et intégration de Cloudflare R2 (compatible S3) avec URLs présignées pour une livraison de médias sécurisée et évolutive sans goulot d'étranglement serveur;Synchronisation d'état en temps réel - Résolution du problème complexe de maintien de la cohérence de l'état des messages entre plusieurs clients connectés en utilisant les salles Socket.IO et la diffusion d'événements;Routage de messages basé sur les salles - Développement d'un système d'abonnement automatique des utilisateurs aux salles personnelles et de groupe lors de la connexion pour une livraison de messages ciblée sans surcharge;Suivi des accusés de lecture multi-utilisateurs - Implémentation d'un système efficace d'accusés de lecture suivant le statut de lecture individuel pour chaque utilisateur dans les chats de groupe sans problèmes de requêtes N+1;Gestion de connexion WebSocket - Construction d'une logique de reconnexion robuste avec backoff exponentiel et récupération d'état après interruptions réseau;Optimisation du schéma de base de données - Conception de modèles Prisma avec indexation stratégique sur les champs fréquemment interrogés (email, username, roomId, createdAt) pour des temps de requête inférieurs à 50ms",

  "project.syntrix.title": "Syntrix",
  "project.syntrix.description":
    "Plateforme full-stack moderne pour cabinets d'avocats avec gestion de clients, traitement sécurisé de documents et système de vérification KYC prévu pour la conformité réglementaire.",
  "project.syntrix.category": "Full-Stack / Legal Tech",
  "project.syntrix.impact":
    "Architecture monorepo avec 72,8% de couverture TypeScript",
  "project.syntrix.fullDescription":
    "Une plateforme de services juridiques de niveau entreprise conçue pour les cabinets d'avocats et les avocats indépendants afin de digitaliser leur pratique. Construite avec une architecture monorepo moderne utilisant Yarn Workspaces, la plateforme dispose d'une API backend NestJS et d'un frontend Next.js avec React 19. L'application est conteneurisée avec Docker et inclut des tests complets, des outils de qualité de code et suit les meilleures pratiques de l'industrie. Conçue avec la sécurité et la conformité à l'esprit, avec des capacités de vérification KYC/AML prévues pour répondre aux exigences réglementaires de l'industrie juridique.",
  "project.syntrix.features":
    "Architecture monorepo moderne avec Yarn Workspaces pour un partage de code efficace et une gestion des dépendances;Frontend Next.js 15 avec App Router, Server Components et React 19 pour des performances optimales;Backend NestJS 11 avec architecture modulaire, injection de dépendances et sécurité de type TypeScript;Design responsive mobile-first avec Tailwind CSS 4 pour une expérience fluide sur tous les appareils;Configuration Docker Compose pour des environnements de développement et de production cohérents;Menu CLI interactif pour un démarrage facile du projet et une sélection d'environnement;Formatage de code automatisé avec Prettier sur toute la base de code;Configuration ESLint complète avec règles spécifiques TypeScript et pratiques recommandées;Infrastructure de tests Jest pour tests unitaires, tests E2E et rapports de couverture de code;Rechargement à chaud et rafraîchissement rapide pour un retour instantané pendant le développement;Optimisation des images Next.js avec chargement paresseux automatique et images réactives;Gestion des variables d'environnement avec validation et sécurité de type;Configuration de déploiement prête pour la production pour Vercel et AWS;Intégration de la famille de polices Geist pour une typographie moderne et professionnelle;Fractionnement de code et tree shaking pour des tailles de bundle optimales",
  "project.syntrix.challenges":
    "Configuration monorepo - Architecture d'une configuration Yarn Workspaces évolutive gérant plusieurs applications (front/back) avec des dépendances partagées, réduisant la taille du bundle de 40% grâce à la déduplication des packages;Mode strict TypeScript sur toute la pile - Application d'une vérification de type stricte sur 72,8% de la base de code TypeScript, éliminant les erreurs de type à l'exécution et améliorant l'intellisense de l'IDE;Orchestration multi-services Docker - Conception de configuration Docker Compose gérant les services frontend, backend et base de données avec mise en réseau appropriée, persistance des volumes et vérifications de santé;Optimisation du workflow de développement - Construction d'un outil CLI interactif personnalisé avec Inquirer pour un démarrage de projet rationalisé, réduisant le changement de contexte et améliorant l'expérience développeur;Migration Next.js 15 App Router - Implémentation réussie de la nouvelle architecture App Router avec composants serveur et client, optimisant le chargement initial de page de 50%;Automatisation de la qualité du code - Intégration d'ESLint avec parser TypeScript et Prettier pour formatage automatisé, appliquant un style de code cohérent sur les contributions de l'équipe;Implémentation de stratégie de test - Établissement d'une infrastructure de test complète avec Jest supportant tests unitaires, tests d'intégration et tests E2E avec rapports de couverture;Optimisation de build - Configuration du compilateur SWC pour des builds plus rapides (20x plus rapide que Babel) et optimisation des bundles de production avec tree shaking",
  "project.syntrix.plannedFeatures":
    "Module KYC/AML - Système complet de vérification Know Your Customer avec téléchargement de documents, vérification OCR, validation d'identité et contrôle de conformité pour exigences réglementaires;Portail Client - Tableau de bord sécurisé pour que les clients puissent consulter l'état des dossiers, télécharger des documents et communiquer avec les avocats;Système de Gestion de Documents - Stockage sécurisé centralisé avec contrôle de version, permissions d'accès et piste d'audit pour documents juridiques;Planification de Rendez-vous - Intégration calendrier avec rappels automatisés et détection de conflits pour réunions clients;Facturation & Facturation - Suivi du temps, gestion des dépenses et génération automatisée de factures avec traitement des paiements;Gestion de Dossiers - Système complet pour suivre les dossiers, échéances, audiences et documents associés avec automatisation du workflow;Messagerie Sécurisée - Communication chiffrée de bout en bout entre avocats et clients avec accusés de lecture et partage de fichiers;Contrôle d'Accès Basé sur les Rôles - Système de permissions granulaires pour associés, collaborateurs, parajuristes et clients;Intégration de Criblage AML - Criblage automatisé contre les listes de sanctions internationales et bases de données PEP;Conformité RGPD/Confidentialité - Fonctionnalités de protection des données incluant export de données, suppression, gestion du consentement et journaux d'audit;Support Multi-langues - Internationalisation pour servir des clients dans plusieurs juridictions;Tableau de Bord Analytique - Business intelligence avec statistiques de dossiers, suivi des revenus et métriques de performance",

  "project.coverLetter.title":
    "Générateur de Lettres de Motivation IA - Extension Chrome",
  "project.coverLetter.description":
    "Extension Chrome intelligente qui génère automatiquement des lettres de motivation personnalisées en analysant les offres d'emploi en temps réel et en les associant aux CV des utilisateurs grâce à une technologie IA avancée.",
  "project.coverLetter.category": "Full-Stack / Extension Navigateur / IA",
  "project.coverLetter.impact":
    "Monorepo avec 92,8% TypeScript - Extension navigateur en production",
  "project.coverLetter.fullDescription":
    "Une extension Chrome sophistiquée propulsée par l'IA qui révolutionne le processus de candidature en générant automatiquement des lettres de motivation sur mesure. L'extension extrait intelligemment le contenu des offres d'emploi depuis n'importe quelle page carrières, analyse les exigences avec l'IA et crée des lettres de motivation personnalisées parfaitement alignées avec le CV du candidat. Construite avec une architecture monorepo comprenant une interface d'extension Chrome en React et une API backend robuste en NestJS, l'application exploite DeepSeek AI pour le traitement du langage naturel et supporte la génération multilingue, s'adaptant automatiquement à la langue de l'offre d'emploi.",
  "project.coverLetter.features":
    "Extraction en temps réel des offres d'emploi depuis n'importe quel site carrières via scripts de contenu et manipulation DOM;Analyse HTML intelligente pour extraire titre du poste, entreprise, description, exigences et qualifications;Génération de lettres de motivation propulsée par l'IA utilisant DeepSeek LLM avec prompts et instructions personnalisables;Détection et correspondance automatique de la langue - génère des lettres dans la même langue que l'offre d'emploi;Authentification Google OAuth 2.0 avec gestion sécurisée des tokens JWT et rotation des tokens de rafraîchissement;Téléchargement de CV et traitement OCR avec Tesseract.js pour extraire le texte des documents PDF;Capacités d'analyse PDF pour lire les CV existants et extraire le contenu structuré;Système d'instructions personnalisées permettant aux utilisateurs d'accentuer des compétences spécifiques ou d'ajuster ton/longueur;Fonctionnalité de copie en un clic vers le presse-papiers pour soumission instantanée de candidature;Fonction d'export PDF pour télécharger les lettres de motivation générées en format professionnel;Interface popup d'extension Chrome avec design glassmorphique moderne et arrière-plans en dégradé;Mise en cache dans le stockage local de la dernière lettre générée pour éviter les appels API inutiles;Navigation par onglets (Générer, Profil, Paramètres) avec transitions fluides;Messages de statut et états de chargement avec indicateurs de progression en temps réel;Stockage et gestion du contenu des CV dans base de données PostgreSQL avec Prisma;API backend RESTful avec validation appropriée utilisant class-validator et class-transformer;Conteneurisation Docker pour environnements de développement et production cohérents;Intercepteurs Axios pour injection automatique des tokens d'authentification et gestion des erreurs;Permissions d'extension Chrome pour onglets, stockage, scripts et accès à l'onglet actif;Script d'arrière-plan pour extraction persistante des détails d'emploi à travers les onglets",
  "project.coverLetter.challenges":
    "Scraping de contenu cross-origin - Implémentation de scripts de contenu d'extension Chrome avec permissions appropriées (host_permissions pour https://*/*) pour injecter des scripts dans les pages d'offres d'emploi et extraire des données structurées depuis diverses mises en page HTML sur différentes plateformes carrières;Analyse de sites web dynamiques - Construction d'algorithmes robustes de parcours DOM pour gérer des structures HTML variées de différentes entreprises (LinkedIn, Indeed, Greenhouse, Lever, etc.), utilisant plusieurs sélecteurs de secours pour assurer une extraction fiable des détails d'emploi;Ingénierie de prompts IA - Création de prompts sophistiqués multi-parties qui analysent à la fois HTML brut et contenu textuel extrait (jusqu'à 120K caractères), instruisant DeepSeek AI pour générer des lettres de motivation authentiques sans inventer d'expérience, maintenant des contraintes de longueur de 250-350 mots;Précision OCR des CV - Intégration de Tesseract.js pour reconnaissance optique de caractères sur CV PDF scannés, implémentation de techniques de prétraitement pour améliorer la précision d'extraction de texte depuis divers formats et mises en page de documents;Flux d'authentification d'extension Chrome - Résolution du défi complexe d'authentification en implémentant le stockage sécurisé de tokens JWT dans chrome.storage.local, avec rafraîchissement automatique de token avant les appels API et gestion transparente des redirections Google OAuth;Génération PDF dans le navigateur - Implémentation de création PDF côté client utilisant la bibliothèque jsPDF, formatant le contenu de lettre de motivation avec marges, polices et style professionnel appropriés sans dépendance backend;Gestion d'état d'extension - Conception de pattern de hooks React (useCoverLetterGenerator, useAuth, useApi) pour gérer des workflows asynchrones complexes incluant requêtes d'onglets, passage de messages et appels API dans le contexte d'extension Chrome;Détection et correspondance de langue - Implémentation d'analyse de langue intelligente dans le prompt IA pour assurer que la langue de la lettre de motivation correspond à l'offre d'emploi, gérant les cas limites avec contenu multilingue et maintenant un ton professionnel dans toutes les langues;Gestion d'erreurs API et logique de retry - Construction de gestion d'erreurs complète avec messages de statut conviviaux, retry automatique pour requêtes échouées et dégradation gracieuse quand le CV est manquant;Coordination d'architecture monorepo - Configuration de Yarn Workspaces pour gérer les types et dépendances partagés entre extension et backend, assurant la sécurité de type sur toute la pile avec configurations TypeScript cohérentes",
  "project.coverLetter.architecture":
    "Extension Chrome (Plasmo) - Interface utilisateur popup basée sur React avec TypeScript, scripts de contenu pour scraping DOM et service worker d'arrière-plan;API Backend (NestJS) - Architecture modulaire avec Controllers, Services et DTOs pour génération de lettres de motivation et gestion de documents;Couche Base de Données (Prisma + PostgreSQL) - ORM pour profils utilisateurs, stockage de CV et gestion de tokens d'authentification;Intégration IA - Client API DeepSeek avec prompts personnalisés, ajustement de température (0.7) et limites de tokens max (1000) pour génération optimale;Système d'Authentification - Google OAuth 2.0 avec stratégies Passport, génération de tokens JWT et rotation des tokens de rafraîchissement;Configuration Docker - Orchestration multi-conteneurs avec Docker Compose pour backend, base de données et environnement de développement",
  "project.coverLetter.technicalHighlights":
    "Injection de Script de Contenu - Exécution dynamique de script via chrome.scripting.executeScript() pour extraction isolée des détails d'emploi;Protocole de Passage de Messages - Messagerie d'extension Chrome entre popup, scripts de contenu et worker d'arrière-plan pour communication inter-contextes;APIs Type-Safe - Couverture TypeScript complète (92,8%) avec interfaces partagées entre extension et backend pour JobDetails, User et réponses API;Pipeline de Validation - Décorateurs Class-validator sur DTOs (GenerateCoverLetterDto) assurant l'intégrité des données avant traitement IA;Stockage Sécurisé - Stockage local Chrome pour mise en cache avec considérations de chiffrement pour tokens d'authentification sensibles;Pattern Instance Axios - Classe de service API centralisée avec intercepteurs requête/réponse pour authentification et gestion d'erreurs;Pattern Hooks React - Hooks personnalisés pour authentification (useAuth), récupération de données (useApi) et logique métier (useCoverLetterGenerator);Pipeline de Traitement PDF - Gestion de documents multi-étapes : téléchargement → OCR (Tesseract) → extraction de texte (pdf-parse) → stockage (Prisma)",
  "project.coverLetter.userFlow":
    "L'utilisateur installe l'extension Chrome et s'authentifie via Google OAuth;L'utilisateur télécharge son CV (PDF) qui est traité via OCR et stocké dans la base de données;L'utilisateur navigue vers n'importe quelle page d'offre d'emploi (LinkedIn, Indeed, site web d'entreprise);L'utilisateur ouvre le popup d'extension et entre optionnellement des instructions personnalisées;L'utilisateur clique sur 'Générer Lettre de Motivation' déclenchant l'extraction des détails d'emploi depuis l'onglet actuel;L'extension envoie le HTML de l'emploi, le texte extrait et le CV de l'utilisateur à l'API backend;DeepSeek AI analyse les exigences de l'emploi et génère une lettre de motivation personnalisée;La lettre générée apparaît dans le popup avec options de copie et téléchargement PDF;L'utilisateur peut régénérer avec différentes instructions ou sauvegarder pour utilisation ultérieure",

  "project.rlSuite.title":
    "Suite d'Apprentissage par Renforcement - Agent IA Multi-Environnements",
  "project.rlSuite.description":
    "Projet complet d'apprentissage par renforcement implémentant les algorithmes Q-Learning, SARSA et Deep Q-Network (DQN) sur plusieurs environnements de jeu incluant Gymnasium classique et jeux Atari.",
  "project.rlSuite.category": "IA/ML / Apprentissage par Renforcement",
  "project.rlSuite.impact":
    "100% Python - Projet de recherche académique pour Epitech MSc Pro",
  "project.rlSuite.fullDescription":
    "Un projet d'intelligence artificielle avancé explorant plusieurs algorithmes d'apprentissage par renforcement appliqués à divers environnements de jeu. Le projet démontre la maîtrise des concepts fondamentaux du RL (Q-Learning, SARSA) sur les environnements Gymnasium classiques, et s'étend à l'apprentissage par renforcement profond de pointe avec l'implémentation DQN pour Atari Pong. Réalisé dans le cadre du programme Master d'Epitech (T-AIA-902), cette suite présente le pipeline complet depuis l'implémentation des algorithmes jusqu'à l'entraînement, l'évaluation et le déploiement des modèles avec des modèles pré-entraînés.",
  "project.rlSuite.features":
    "Implémentation Q-Learning pour l'environnement Frozen Lake 8x8 avec glissance configurable;Algorithme SARSA (State-Action-Reward-State-Action) pour l'apprentissage on-policy;Deep Q-Network (DQN) avec experience replay et target network pour Atari Pong;Environnement Cliff Walking avec implémentations Q-Learning et SARSA pour comparaison;Environnement Taxi Driver avec Q-Learning optimisé pour navigation complexe;Persistance des modèles avec formats pickle (.pkl) et PyTorch (.pt) pour réutilisabilité;Mode de jeu interactif pour tester les agents entraînés en temps réel avec rendu lisible;Intégration TensorBoard pour visualisation de l'entraînement et suivi des métriques de performance;Accélération GPU avec CUDA pour entraînement DQN plus rapide sur environnements complexes;Stratégie d'exploration epsilon-greedy avec décroissance pour équilibre exploitation-exploration optimal;Base de code modulaire avec scripts d'entraînement et de test séparés pour chaque environnement;Documentation complète avec rapport PDF détaillé et slides de présentation;Rendu visuel avec Pygame pour observation humaine du comportement de l'agent;Hyperparamètres configurables (taux d'apprentissage, facteur de réduction, décroissance epsilon);Modèles pré-entraînés inclus pour test et démonstration immédiats",
  "project.rlSuite.challenges":
    "Optimisation convergence Q-Table - Ajustement du taux d'apprentissage (alpha) et facteur de réduction (gamma) pour atteindre 95%+ de taux de succès sur Frozen Lake, équilibrant exploration vs exploitation avec stratégie de décroissance epsilon-greedy;Problème d'attribution de crédit dans récompenses éparses - Implémentation de mises à jour efficaces des Q-values pour Cliff Walking où les récompenses n'apparaissent qu'à l'état objectif, utilisant l'apprentissage par différence temporelle pour propager la valeur en arrière;Stabilité et convergence DQN - Résolution des problèmes notoires d'instabilité du RL profond en implémentant un buffer d'experience replay (stockant 10K+ transitions) et réseau cible séparé mis à jour tous les N épisodes pour briser la corrélation dans les données d'entraînement;Gestion espace d'états haute dimension - Conception d'architecture réseau neuronal convolutif pour Atari Pong traitant des frames de 84x84 pixels, utilisant l'empilement de frames (4 frames consécutives) pour capturer mouvement et vélocité;Oubli catastrophique dans réseaux neuronaux - Atténué par mécanisme d'experience replay échantillonnant des mini-batchs aléatoires de la mémoire, empêchant le réseau d'oublier les stratégies apprises précédemment;Optimisation temps d'entraînement - Utilisation de l'accélération GPU CUDA et traitement parallèle d'environnements pour réduire le temps d'entraînement DQN de 40+ heures à moins de 8 heures sur jeux Atari complexes;Stochasticité de l'environnement - Gestion des transitions non déterministes de Frozen Lake (mode is_slippery) en s'entraînant pour plus d'épisodes et en moyennant les Q-values pour apprendre des politiques robustes;Façonnage de récompense pour apprentissage plus rapide - Analyse et ajustement des structures de récompense dans Taxi Driver pour inciter au ramassage/dépôt efficace de passagers tout en pénalisant les mouvements inutiles",
  "project.rlSuite.algorithms":
    "Q-Learning (Contrôle TD Off-Policy) - Algorithme sans modèle apprenant la fonction valeur-action optimale indépendamment de la politique actuelle de l'agent;SARSA (Contrôle TD On-Policy) - Met à jour les Q-values basées sur l'action réellement prise par la politique actuelle, plus conservateur que Q-Learning;Deep Q-Network (DQN) - Combine Q-Learning avec réseaux neuronaux profonds pour gérer les entrées visuelles haute dimension depuis pixels bruts;Experience Replay - Stocke les transitions dans un buffer de replay et échantillonne des mini-batchs aléatoires pour briser les corrélations temporelles;Target Network - Réseau séparé pour générer les cibles de Q-value, mis à jour périodiquement pour stabiliser l'entraînement;Exploration Epsilon-Greedy - Équilibre exploration aléatoire avec exploitation gloutonne, avec calendrier de décroissance exponentielle",
  "project.rlSuite.environments":
    "Frozen Lake 8x8 - Naviguer dans un monde grille glacé en évitant les trous pour atteindre l'objectif, avec transitions stochastiques optionnelles;Cliff Walking - Marcher le long du bord de falaise pour atteindre l'objectif tout en évitant de tomber (récompense négative élevée);Taxi Driver - Tâche multi-objectifs : naviguer dans la grille, ramasser passager, déposer à destination efficacement;Atari Pong - Jeu d'arcade classique nécessitant traitement visuel et raisonnement temporel pour battre l'adversaire",

  "project.voiceTrain.title":
    "Système de Recherche d'Itinéraires Ferroviaires par Commande Vocale avec NER & Base de Données Graphe",
  "project.voiceTrain.description":
    "Système IA de traitement du langage naturel qui comprend des requêtes vocales pour rechercher les itinéraires ferroviaires français optimaux en utilisant BERT pour la reconnaissance d'entités nommées et Neo4j pour la navigation dans les graphes.",
  "project.voiceTrain.category":
    "IA/ML / Traitement du Langage Naturel / Base de Données Graphe",
  "project.voiceTrain.impact": "100% Python - Projet de Recherche Académique",
  "project.voiceTrain.fullDescription":
    "Un système d'intelligence artificielle sophistiqué qui combine reconnaissance vocale, traitement du langage naturel et bases de données graphe pour créer une interface intuitive de recherche d'itinéraires ferroviaires. Le projet utilise des modèles de transformers de pointe (BERT, CamemBERT) pour extraire les entités nommées (NER) des requêtes en langage naturel, stocke le réseau ferroviaire français dans une base de données graphe Neo4j, et applique l'algorithme de Dijkstra pour trouver les chemins optimaux. Réalisé dans le cadre du programme Master, ce projet démontre la maîtrise de l'apprentissage profond, des systèmes de dialogue et des bases de données graphe pour des applications réelles.",
  "project.voiceTrain.features":
    "Reconnaissance vocale en temps réel avec support multilingue (français, anglais, espagnol, arabe);Fine-tuning de BERT pour la reconnaissance d'entités nommées spécifique au domaine ferroviaire;Reconnaissance d'entités avec spaCy 3.7 pour extraction de villes, dates, heures et types de trains;Base de données graphe Neo4j 5.25 modélisant 148 gares françaises connectées par 179 liaisons ferroviaires;Algorithme de Dijkstra pour recherche de plus court chemin avec pondération par distance;Interface en ligne de commande (CLI) interactive pour saisie utilisateur et affichage des résultats;Pipeline de traitement multi-étapes : Parole → Texte → Entités → Requête → Résultats;Analyse de notebooks Jupyter pour prétraitement des données, entraînement de modèles et évaluation;Augmentation de données pour améliorer la robustesse du modèle sur requêtes variées;Vectorisation de texte avec TF-IDF et représentations word embeddings;Fine-tuning de CamemBERT (BERT français) pour améliorer les performances sur texte français;Requêtes Neo4j Cypher pour recherche efficace dans les graphes et récupération de chemins;Système d'annotations personnalisé pour créer des données d'entraînement NER spécifiques au domaine;Évaluation de modèle avec métriques de précision, rappel et score F1 pour les entités extraites;Système de gestion d'erreurs pour requêtes invalides et gares non trouvées;Conteneurisation Docker pour environnement Neo4j cohérent;Scripts de chargement de données pour ingestion de CSV dans base de données graphe;Reconnaissance vocale hors ligne utilisant le moteur Vosk comme alternative;Comparaison de modèles entre BERT base et fine-tuné pour NER",
  "project.voiceTrain.challenges":
    "Fine-tuning de modèle NER spécifique au domaine - Adaptation de BERT pré-entraîné pour reconnaître des entités spécifiques au rail (noms de gare, types de train) non présentes dans les datasets standard NER, nécessitant un annotation de dataset personnalisé avec 500+ exemples et fine-tuning avec taux d'apprentissage 2e-5 sur 20 époques;Déséquilibre de dataset - Résolution du problème de déséquilibre de classes sévère où certaines entités (villes populaires) apparaissent 10x plus fréquemment que d'autres, utilisant sur-échantillonnage de classes minoritaires, pondération de perte et augmentation de données avec paraphrases;Hétérogénéité de la parole - Gestion de la variabilité des accents, vitesses de parole et qualité microphone en testant plusieurs moteurs de reconnaissance vocale (Google, Vosk) et implémentation de filtrage pré-traitement (réduction du bruit, normalisation d'amplitude);Ingénierie de requêtes graphe - Optimisation des requêtes Neo4j Cypher pour recherche de chemin efficace sur graphes 148 nœuds/179 arêtes, créant index sur propriétés de nœuds gares et utilisant paramètres de requête pour éviter le scan complet du graphe;Variations de langage naturel - Traitement des innombrables façons dont utilisateurs peuvent exprimer la même requête ('train de Paris à Lyon' vs 'aller à Lyon depuis Paris'), résolu par augmentation de données avec templates et utilisation de modèles de langage pré-entraînés capturant sémantique;Intégration de pipelines multi-modèles - Coordination du flux de travail entre modèle de reconnaissance vocale, modèle BERT NER, analyseur spaCy et requêtes base de données avec gestion d'erreurs appropriée et logging à chaque étape;Incompatibilité des versions de dépendances - Résolution des conflits entre PyTorch 2.x, TensorFlow, spaCy 3.7 et Transformers en créant environnement conda isolé avec résolution de dépendances stricte et fix de versions dans requirements.txt;Contraintes mémoire GPU - Optimisation de l'entraînement de modèle BERT sur GPU standard (8GB VRAM) en utilisant accumulation de gradient (taille de batch effective 16 avec accumulation 4-étapes), mixed precision training et gradient checkpointing;Nettoyage et normalisation de données - Prétraitement du dataset brut de gares françaises avec noms incohérents, valeurs manquantes et encodage, implémentation d'une pipeline robuste de nettoyage avec matching flou et détection de doublons;Modélisation de données graphe - Conception d'un schéma Neo4j efficace représentant le réseau ferroviaire avec nœuds pour gares, relations pour connexions ferroviaires, propriétés pour distances/temps de trajet, équilibrant normalisation avec performance de requête",
  "project.voiceTrain.architecture":
    "Couche Reconnaissance Vocale - Module d'entrée audio avec PyAudio capturant voix, moteurs STT (Google Speech Recognition, Vosk) transcrivant en texte;Couche Traitement NLP - Pipeline spaCy 3.7 pour tokenisation et extraction d'entités, modèle BERT/CamemBERT fine-tuné pour NER détectant noms de gare, dates, heures;Couche Base de Données Graphe - Neo4j 5.25 stockant réseau ferroviaire sous forme de graphe (gares = nœuds, connexions ferroviaires = arêtes) avec propriétés pondérées par distance;Couche Recherche de Chemin - Implémentation d'algorithme de Dijkstra interrogeant Neo4j via Cypher pour trouver routes optimales entre origine et destination;Notebooks Jupyter - Environnement d'analyse pour exploration de données, entraînement de modèles (TensorFlow/Keras), évaluation et visualisation de métriques de performance;Application CLI - Interface utilisateur interactive basée sur Python construite pour démonstration du pipeline de bout en bout et tests utilisateur",
  "project.voiceTrain.technicalComponents":
    "Modèles de Transformers - Fine-tuning de BERT (bert-base-multilingual-cased) et CamemBERT avec Hugging Face Transformers pour reconnaissance d'entités;Pipeline NER spaCy - Composants NER personnalisés entraînés sur données spécifiques au domaine ferroviaire avec types d'entités STATION, DATE, TIME, TRAIN_TYPE;API Python Neo4j - Client py2neo pour connexion base de données, exécution de requêtes Cypher et récupération de chemins graphe;Algorithme de Plus Court Chemin - Implémentation Neo4j de Dijkstra utilisant propriétés pondérées par distance pour recherche de route optimale;Framework d'Entraînement - Boucles d'entraînement PyTorch/Keras avec callbacks pour early stopping, réduction de taux d'apprentissage et checkpointing de modèle;Pipeline de Prétraitement de Données - Scripts Pandas pour nettoyage CSV, normalisation et ingestion dans Neo4j avec gestion de doublons",
  "project.voiceTrain.notebooks":
    "NER_Bert.ipynb - Fine-tuning de BERT pour reconnaissance d'entités nommées avec dataset personnalisé, évaluation de métriques et comparaison de modèles;TF_IDF_model.ipynb - Approche baseline de classification de texte utilisant vectorisation TF-IDF et algorithmes ML traditionnels;Bert_Train_Stations.ipynb - Dataset de gares ferroviaires françaises, analyse exploratoire de données et préparation pour injection Neo4j;Exploration diverses - Notebooks additionnels pour expérimentation d'augmentation de données, réglage d'hyperparamètres et analyse d'erreurs",
  "project.voiceTrain.dataFlow":
    "L'utilisateur parle une requête en langage naturel dans le microphone (ex : 'Je veux aller de Paris à Marseille');Le module de reconnaissance vocale transcrit l'audio en texte utilisant moteur STT;Le pipeline spaCy tokenise le texte et le modèle BERT NER extrait les entités (origine: Paris, destination: Marseille);Les noms de gare extraits sont utilisés pour construire une requête Neo4j Cypher recherchant le plus court chemin;Neo4j exécute l'algorithme de Dijkstra et retourne la route optimale avec gares intermédiaires et distance totale;L'application CLI formate et affiche les résultats à l'utilisateur en langage lisible",
  "project.voiceTrain.usageExamples":
    "Requête simple: 'Train de Lyon à Toulouse' → Extrait origine (Lyon) et destination (Toulouse) → Retourne chemin le plus court;Requête multilingue: 'I want to go from Nice to Bordeaux' → Traite requête anglaise → Retourne route dans réseau français;Requête complexe: 'Prochain TGV de Paris Gare de Lyon à Marseille Saint-Charles demain matin' → Extrait plusieurs entités incluant type de train et contraintes temporelles;Requête manquante: 'Train vers Montpellier' → Détecte destination manquante → Demande à l'utilisateur de clarifier origine",

  "project.jumbot.title":
    "Jumbot - Bot de Déploiement Automatisé pour la Plateforme Storiz LCMS",
  "project.jumbot.description":
    "Outil d'automatisation interne construit comme un bot Slack pour rationaliser les processus de déploiement du système de gestion de contenu d'apprentissage Storiz, éliminant les goulots d'étranglement DevOps manuels et permettant aux équipes non techniques de déployer des applications de manière indépendante.",
  "project.jumbot.category":
    "Automatisation DevOps / Outillage Interne / Développement de Bot",
  "project.jumbot.impact":
    "Temps de déploiement réduit de 1 semaine à quelques minutes - Outil interne pour Groupe Bizness/Actual Digital Factory",
  "project.jumbot.fullDescription":
    "Jumbot est un bot Slack complet conçu pour automatiser le processus de déploiement complexe de la plateforme Storiz LCMS. Auparavant, les équipes commerciales non techniques devaient contacter les développeurs et ingénieurs DevOps pour chaque déploiement client, créant des goulots d'étranglement pouvant prendre jusqu'à une semaine. Jumbot transforme ce flux de travail en fournissant une interface Slack intuitive où les utilisateurs peuvent déployer, mettre à jour, lister et supprimer des environnements Storiz via de simples commandes slash. Le système gère plusieurs sous-applications (learniz, back-office, front-dynamic, game, back, game-scorm, learniz-scorm) avec des configurations personnalisées pour chaque client. Construit avec une architecture microservices utilisant BoltJS pour l'intégration Slack, NestJS pour la logique métier, RabbitMQ pour les files de messages et MongoDB pour la persistance des données, Jumbot démontre une automatisation de niveau entreprise tout en maintenant sécurité et traçabilité.",
  "project.jumbot.features":
    "Interface de commandes slash Slack (/storiz-deploy-env, /storiz-list-env, /storiz-update-env, /storiz-delete-env);Génération dynamique de modales avec intégration API GitLab pour sélection de branches;Support de déploiement multi-applications (7 sous-applications Storiz différentes);Notifications de statut de déploiement en temps réel avec mentions utilisateurs;Piste d'audit complète avec suivi UUID pour toutes les opérations;Validation et sélection de branches GitLab via intégration API;Stockage de configuration basé sur MongoDB avec gestion des rôles utilisateurs;File de messages RabbitMQ pour traitement de déploiement asynchrone;Gestion d'erreurs avec notifications d'échec automatiques;Conteneurisation Docker avec orchestration Kubernetes;Exécution de scripts Bash pour opérations de déploiement côté serveur;Gestion des permissions utilisateurs et contrôle d'accès basé sur les rôles;Liste d'environnements avec affichage détaillé de configuration;Capacités de rollback automatique de déploiement;Intégration avec pipelines CI/CD existants;Compatibilité multi-plateforme (mobile, desktop, web via Slack);Intégration de chat en temps réel pour coordination de déploiement;Nommage d'environnement personnalisé avec validation regex (^[a-z]+$);Support de déploiement multi-branches pour dépôts front-end et back-end",
  "project.jumbot.challenges":
    "Conception d'architecture microservices complexe - Construction d'un système distribué avec BoltJS (interface Slack), NestJS (logique métier), RabbitMQ (messagerie) et MongoDB (persistence), assurant protocoles de communication appropriés (HTTP, AMQP, TCP) et maintenant standards de sécurité élevés entre services;Intégration API Slack et développement de modales - Implémentation de génération dynamique de formulaires utilisant le framework Block Kit de Slack, gérant entrées utilisateurs, validations et mises à jour en temps réel tout en gérant les limites de taux API Slack et exigences webhook;Intégration API GitLab pour gestion de branches - Développement d'un système automatisé de découverte et validation de branches, gérant authentification GitLab, pagination API et listing de branches en temps réel pour dépôts front-end et back-end;Traitement de déploiement asynchrone - Conception d'un système robuste de file de messages avec RabbitMQ pour gérer opérations de déploiement longues, implémentant gestion d'erreurs appropriée, gestion de timeouts et suivi de statut à travers composants distribués;Implémentation de sécurité et contrôle d'accès - Construction d'un système complet d'authentification et autorisation utilisateur, intégration avec rôles utilisateurs Slack, implémentation de suivi de session basé UUID et assurance de communication sécurisée entre tous les microservices;Conception de base de données pour audit et configuration - Architecture de schéma MongoDB pour stockage de configurations de déploiement, permissions utilisateurs, mappings GitLab et journaux d'audit complets avec capacités de requêtage efficaces;Gestion d'erreurs et retour utilisateur - Implémentation d'un système sophistiqué de propagation d'erreurs depuis scripts bash côté serveur via RabbitMQ vers Slack, fournissant messages d'erreur significatifs et mécanismes de retry automatisés;Configuration d'environnement de développement avec ngrok - Résolution des défis de développement local en implémentant tunneling ngrok pour test de webhooks Slack, permettant flux de travail de développement fluide avec intégration API live;Intégration de scripts Bash et communication serveur - Développement d'exécution sécurisée de scripts de déploiement sur serveur Fondue distant, gérant prévention d'injection de commandes, parsing de sortie et reporting de statut en temps réel;Intégration de pipeline CI/CD - Intégration de Jumbot avec flux de travail GitLab CI/CD existants, assurant cohérence de déploiement et maintenant compatibilité avec pratiques DevOps établies",
  "project.jumbot.architecture":
    "Couche Interface Slack - Framework BoltJS gérant commandes slash, interactions modales et notifications utilisateurs;Couche API Gateway - Microservice NestJS gérant logique métier, validation et orchestration;Couche File de Messages - RabbitMQ gérant communication asynchrone entre services;Couche Base de Données - MongoDB pour stockage de configuration et PostgreSQL pour journaux d'audit;Couche Déploiement - Serveur Fondue exécutant scripts bash pour déploiement réel d'application;Couche Intégration Externe - API GitLab pour gestion de branches et API Slack pour interface utilisateur",
  "project.jumbot.technicalComponents":
    "Bot Slack BoltJS - Commandes slash personnalisées, modales interactives et notifications en temps réel;Microservice NestJS - API RESTful avec TypeScript, pipes de validation et logique métier;Broker de Messages RabbitMQ - Échanges directs, files et traitement de messages asynchrone;Base de Données MongoDB - Stockage basé sur documents pour configurations, utilisateurs et historique de déploiement;Conteneurs Docker - Déploiement conteneurisé avec orchestration Kubernetes;Intégration GitLab CI/CD - Déclenchements de pipeline automatisés et validation de branches",
  "project.jumbot.usageExamples":
    "Déployer: /storiz-deploy-env → Sélectionner branches et applications → Déploiement automatique avec notifications;Lister: /storiz-list-env → Voir tous les environnements déployés avec configurations;Mettre à jour: /storiz-update-env nomEnvironnement → Sélectionner nouvelles applications à ajouter/supprimer;Supprimer: /storiz-delete-env nomEnvironnement → Nettoyage complet d'environnement;Aide: /storiz-help-env → Afficher documentation d'utilisation complète",

  "project.myActual.title":
    "My Actual - Plateforme RH d'Entreprise pour Intérimaires",
  "project.myActual.description":
    "Application web et mobile complète servant des milliers d'intérimaires, candidats et agences à travers la France. Gère missions, contrats, documents, candidatures et communications d'agence avec synchronisation en temps réel entre plateformes.",
  "project.myActual.category":
    "Application Web/Mobile d'Entreprise / Tech RH / Développement Full-Stack",
  "project.myActual.impact":
    "Application en production servant des milliers d'utilisateurs quotidiens à travers la France - Plateforme principale du Groupe Actual pour intérimaires",
  "project.myActual.fullDescription":
    "My Actual est la plateforme digitale centrale du Groupe Actual, une des principales entreprises RH et de recrutement en France. Cette application critique sert d'interface principale pour les intérimaires, candidats et personnel d'agence pour gérer leurs relations professionnelles. La plateforme gère tout, des candidatures et gestion de missions au traitement de contrats et stockage de documents. Construite avec une stack technologique moderne incluant React/TypeScript pour le web, React Native/Expo pour le mobile et Laravel pour les services backend, l'application démontre un développement à échelle d'entreprise avec exigences de haute disponibilité. Le système s'intègre à plusieurs sources de données, fournit notifications en temps réel et maintient synchronisation entre plateformes web et mobile tout en servant des milliers d'utilisateurs concurrents quotidiennement.",
  "project.myActual.features":
    "Disponibilité multi-plateforme (application web responsive et application mobile native);Système de gestion de missions pour visualisation des missions actuelles et passées;Portail de candidatures avec capacités de recherche et filtrage avancées;Système de gestion documentaire (contrats, bulletins de paie, certificats, attestations);Notifications en temps réel pour mises à jour importantes et actions requises;Système de messagerie directe avec représentants d'agence;Gestion de profil utilisateur avec informations professionnelles;Suivi d'historique de missions et analytiques de performance;Capacités de téléchargement et partage de documents;Support multilingue pour base d'utilisateurs diverse;Fonctionnalité hors ligne pour utilisateurs mobiles;Notifications push pour utilisateurs d'application mobile;Recherche avancée avec intégration Elasticsearch;Système de cache avec Redis pour performance améliorée;Système Environment on Demand (EOD) pour test de nouvelles fonctionnalités;Pipeline de tests automatisés avec couverture complète;Contrôle d'accès basé sur les rôles pour différents types d'utilisateurs;Intégration avec services Google Cloud Platform;Synchronisation de données en temps réel entre web et mobile;Design responsive optimisé pour toutes tailles d'appareils",
  "project.myActual.challenges":
    "Modernisation de code legacy - Direction de la migration de JSX vers TSX (TypeScript) et conversion de composants classe vers composants fonctionnels, améliorant sécurité de type et maintenabilité sur une large base de code tout en maintenant compatibilité ascendante;Complexité de développement multi-plateforme - Assurance de parité de fonctionnalités et expérience utilisateur cohérente entre application web React et application mobile React Native, gérant exigences UI/UX spécifiques à la plateforme et tests sur multiples appareils;Optimisation de performance à échelle d'entreprise - Implémentation de stratégies de cache Redis, optimisation de requêtes Elasticsearch et indexation de base de données pour maintenir temps de réponse sous la seconde pour des milliers d'utilisateurs concurrents;Relations de données complexes et logique métier - Navigation dans logique domaine RH complexe impliquant missions, contrats, rôles utilisateurs et relations d'agence tout en maintenant intégrité des données à travers systèmes interconnectés multiples;Défis de synchronisation en temps réel - Développement de mécanismes robustes de synchronisation de données entre plateformes web et mobile, gérant scénarios hors ligne, résolution de conflits et assurance de cohérence de données à travers tous points de contact utilisateur;Tests et assurance qualité - Augmentation de couverture de tests pour composants frontend (JavaScript) et backend (PHP), implémentation de pipelines de tests automatisés et assurance de stabilité pour déploiements en production affectant des milliers d'utilisateurs;Collaboration d'équipe à distance - Adaptation à environnement de travail entièrement à distance, maîtrise de communication asynchrone, processus de revue de code et méthodologies agiles tout en maintenant haute productivité et standards de qualité de code;Investigation et résolution de bugs - Utilisation de BigQuery pour analyse complexe de données pour investiguer problèmes rapportés par utilisateurs, tracer incohérences de données et identifier causes racines de comportements système affectant expérience utilisateur;Gestion d'environnement et déploiement - Travail avec système Environment on Demand (EOD) basé Kubernetes pour test de fonctionnalités, assurant pipelines de déploiement fluides et minimisant risques de production;Optimisation d'expérience utilisateur - Équilibre entre contraintes techniques et besoins utilisateurs, travail étroit avec designers et product managers pour implémenter interfaces intuitives tout en maintenant performance système et fiabilité",
  "project.myActual.architecture":
    "Couche Frontend - React avec TypeScript pour web, React Native avec Expo pour mobile;Couche Backend - Framework Laravel PHP avec architecture API RESTful;Couche Base de Données - PostgreSQL pour données relationnelles avec Redis pour cache;Couche Recherche - Elasticsearch pour capacités de recherche et filtrage avancées;Infrastructure Cloud - Google Cloud Platform avec orchestration Kubernetes;Pipeline CI/CD - Tests et déploiement automatisés avec GitHub Actions",
  "project.myActual.technicalComponents":
    "Frontend React - Architecture moderne basée composants avec TypeScript pour sécurité de type;Application Mobile React Native - Développement mobile multi-plateforme avec framework Expo;Backend Laravel - Framework PHP avec Eloquent ORM et gestion de ressources API;Base de Données PostgreSQL - Base de données relationnelle avec requêtes et indexation optimisées;Moteur Elasticsearch - Capacités de recherche avancée avec indexation en temps réel;Cache Redis - Stockage de structure de données en mémoire pour gestion de session et cache;Services GCP - Hébergement cloud, stockage et intégration de services gérés;Cluster Kubernetes - Orchestration de conteneurs pour gestion de déploiement évolutive",
  "project.myActual.workflowExamples":
    "Développement de Fonctionnalité - Assignation tâche Notion → Développement local → GitHub PR → Revue de code → Tests EOD → Déploiement production;Investigation de Bug - Rapport utilisateur → Analyse données BigQuery → Identification cause racine → Implémentation de correction → Tests → Release;Tests Mobile - Application Expo Go → Tests spécifiques à branche → Validation multi-plateforme → Tests d'acceptation utilisateur;Planification de Sprint - Raffinement backlog → Estimation tâches → Engagement sprint → Standups quotidiens → Rétrospective sprint",
  "project.myActual.teamStructure":
    "Méthodologie Agile avec sprints de 2 semaines et rétrospectives régulières;Standups quotidiens à 9h30 pour synchronisation d'équipe;Sessions de planification hebdomadaires pour priorisation et distribution de tâches;Raffinement de backlog bi-hebdomadaire pour préparation du prochain sprint;Collaboration inter-fonctionnelle avec développeurs, designers et product managers;Équipe remote-first avec communication structurée via Slack et Google Meet",

  // Bot d'accueil
  "welcomeBot.botName": "Guide Portfolio",
  "welcomeBot.status": "En ligne",
  "welcomeBot.skip": "Passer la visite",
  "welcomeBot.previous": "Précédent",
  "welcomeBot.next": "Suivant",
  "welcomeBot.getStarted": "C'est parti !",
  "welcomeBot.step1.title": "Bienvenue sur mon Portfolio !",
  "welcomeBot.step1.message":
    "Salut ! Je suis votre guide personnel. Laissez-moi vous faire découvrir ce qui rend ce portfolio spécial. Prêt à commencer la visite ?",
  "welcomeBot.step2.title": "Navigation & Défilement Fluide",
  "welcomeBot.step2.message":
    "Vous remarquez le défilement fluide ? J'ai implémenté Lenis pour des transitions de page ultra-douces. Vous pouvez aussi utiliser les boutons de navigation ou simplement défiler naturellement à travers chaque section.",
  "welcomeBot.step3.title": "Projets Interactifs",
  "welcomeBot.step3.message":
    "Descendez pour voir mes projets ! Chaque carte est interactive avec des effets d'inclinaison 3D. Cliquez sur n'importe quel projet pour voir des informations détaillées, les défis techniques, les diagrammes d'architecture, et des démos en direct quand disponibles.",
  "welcomeBot.step4.title": "Support Multi-langue",
  "welcomeBot.step4.message":
    "Vous voyez le sélecteur de langue en haut à droite ? Ce portfolio supporte l'anglais et le français. Essayez de changer de langue - tout le contenu est entièrement internationalisé !",
  "welcomeBot.step5.title": "Dans les Coulisses",
  "welcomeBot.step5.message":
    "Curieux de savoir comment cela a été construit ? Cliquez sur le bouton '?' en haut à gauche pour découvrir la stack technique, les animations et le processus de développement. Bonne exploration !",
  "welcomeBot.step6.title": "Télécharger Mon CV",
  "welcomeBot.step6.message":
    "Vous voulez voir mes qualifications complètes ? Cliquez sur le bouton CV en bas à gauche pour consulter mon curriculum vitae en anglais ou en français. Parfait pour un aperçu détaillé de mon expérience !",
  "welcomeBot.step7.title": "Prenez Contact",
  "welcomeBot.step7.message":
    "Prêt à échanger ? Descendez en bas de la page pour trouver le formulaire de contact. Envoyez-moi un message, et je vous répondrai dès que possible. J'aimerais avoir de vos nouvelles !",
};
